//
//  StanCodeGenerator.swift
//  Stan
//
//  Phase 1 of the ulam port: the public, pure (UlamModel) -> String
//  generator. No file I/O, no cmdstan. Phase 2 adds the orchestrator that
//  writes <name>.stan and hands off to compile() / sample().
//

import Foundation

enum StanCodeGenerator {
  /// Lower an `UlamModel` to Stan source.
  ///
  /// Phase 1 supports: scalar fixed-effects models with `normal`,
  /// `bernoulli`, `binomial`, `beta`, `exponential` distributions and
  /// `logit`, `log`, `invLogit` link functions.
  public static func generate(_ model: UlamModel) throws -> String {
    let inferred = try DataInference.classify(model)
    return try assemble(inferred: inferred, statements: model.statements)
  }

  /// Assemble the full Stan source (header + data + parameters + model)
  /// from an already-classified `InferredModel`. Shared between the
  /// pure `generate(_:)` entry point and the file-emitting `ulam(_:)`
  /// orchestrator so both paths produce identical output.
  static func assemble(inferred: InferredModel,
                       statements: [Statement]) throws -> String {
    let header = "// Generated by SwiftStan ulam port."
    let data = BlockEmitter.dataBlock(inferred)
    let params = BlockEmitter.parametersBlock(inferred)
    let modelBlock = try BlockEmitter.modelBlock(inferred, statements: statements)
    // Phase 5.5 Slice E: insert the `transformed parameters` block
    // between `parameters` and `model` when any VaryingPrior was
    // declared with `nonCentered: true`. Centred-only models skip
    // the block entirely and stay byte-identical to v1 output.
    var sections: [String] = [header, data]
    if let td = BlockEmitter.transformedDataBlock(inferred) {
      sections.append(td)
    }
    sections.append(params)
    if let tp = BlockEmitter.transformedParametersBlock(inferred) {
      sections.append(tp)
    }
    sections.append(modelBlock)
    if let gq = BlockEmitter.generated_QuantitiesBlock(inferred) {
      sections.append(gq)
    }
    return sections.joined(separator: "\n")
  }
}

/// Equivalent of R's `stancode()` — return generated Stan source without
/// writing it to disk or compiling it.
public func stancode(_ model: UlamModel) throws -> String {
  try StanCodeGenerator.generate(model)
}
