//
//  AlistEmitter.swift
//  Stan
//
//  Slice E of the alist parser. Renders a `ClassifiedAlist` to a
//  self-contained `@main` Swift smoke driver in the same shape as the
//  bernoulli template in `UlamGeneratorTests.swift:892`. The result is
//  the input that `dsl2stan` consumes downstream.
//
//  Stub data values follow the Q1(b) heuristic from
//  `Docs/AlistParser.md`:
//    - Likelihood outcome of dbinom/dbern/dpois → `.integer([…])`
//    - Index columns (any `[col]` reference) → `.integer([…])`
//    - Everything else → `.real([…])`
//

import Foundation

internal struct AlistEmitter {
  /// Separator the smoke driver prints between the Stan source and the
  /// init JSON. `dsl2stan` looks for this exact string to split stdout
  /// into the two files. Plain Stan comment so a smoke driver that
  /// runs without `dsl2stan` (or against a Stan parser that ingests
  /// stdout) still parses the source half cleanly.
  internal static let initsSentinel = "// === SWIFTSTAN_INITS ==="

  /// Separator the smoke driver prints before the scalar-constants JSON
  /// (e.g. the multivariate dimension `J`). `dsl2stan` splits on this
  /// to write `<name>.scalars.json`, which `csv2json` then merges into
  /// the data JSON. Printed before the inits block when present.
  internal static let scalarsSentinel = "// === SWIFTSTAN_SCALARS ==="

  internal let stem: String      // e.g. "Chimpanzees" → produces ChimpanzeesSmoke
  internal let modelName: String // e.g. "chimpanzees" — the dir name
  internal let classified: ClassifiedAlist

  internal func emit() -> String {
    var s = ""
    appendHeader(&s)
    s += "\n@main\n"
    s += "struct \(stem)Smoke {\n"
    s += "  static func main() {\n"
    appendDataLiteral(&s)
    s += "\n"
    appendModelBlock(&s)
    s += "\n"
    s += "    do {\n"
    s += "      print(try stancode(model))\n"
    s += "      let scalars = stanScalars(model)\n"
    s += "      if !scalars.isEmpty {\n"
    s += "        print(\"\(Self.scalarsSentinel)\")\n"
    s += "        print(scalars)\n"
    s += "      }\n"
    s += "      let inits = try stanInits(model)\n"
    s += "      if !inits.isEmpty {\n"
    s += "        print(\"\(Self.initsSentinel)\")\n"
    s += "        print(inits)\n"
    s += "      }\n"
    s += "    } catch {\n"
    s += "      print(\"ERROR: \\(error)\")\n"
    s += "    }\n"
    s += "  }\n"
    s += "}\n"
    return s
  }

  // MARK: - Header

  private func appendHeader(_ s: inout String) {
    s += "// \(stem).ulam.swift\n"
    s += "//\n"
    s += "// Generated by `stan alist2dsl` from `\(modelName).alist.R`.\n"
    s += "// Edit `\(modelName).alist.R` and re-run `stan alist2dsl` to regenerate.\n"
    s += "// The `data` literal carries one stub row per column — actual values\n"
    s += "// come from `Preliminaries/\(modelName).csv` via `csv2json`.\n"
  }

  // MARK: - Data literal

  private func appendDataLiteral(_ s: inout String) {
    s += "    let data: UlamData = [\n"
    // Order: outcome, vector-length cardinality bindings, index columns,
    // other data columns.
    var emitted: Set<String> = []
    func line(_ key: String, _ kind: String) {
      s += "      \"\(key)\": .\(kind)([\(stubValue(for: key))]),\n"
      emitted.insert(key)
    }
    if !classified.outcome.isEmpty, !emitted.contains(classified.outcome) {
      line(classified.outcome, columnKind(name: classified.outcome))
    }
    // Bind synthesised cardinality symbols (e.g. "J": .scalarInt(2)).
    // Sort for deterministic output.
    for (sym, len) in classified.lengthBindings.sorted(by: { $0.key < $1.key })
      where !emitted.contains(sym) {
      s += "      \"\(sym)\": .scalarInt(\(len)),\n"
      emitted.insert(sym)
    }
    for col in classified.indexColumns where !emitted.contains(col) {
      line(col, "integer")
    }
    for col in classified.dataColumns where !emitted.contains(col) {
      line(col, columnKind(name: col))
    }
    s += "    ]\n"
  }

  /// Type heuristic — shared with `AlistToUlamModel` via
  /// `ClassifiedAlist.stubKind(for:)` in `AlistClassify.swift`.
  private func columnKind(name: String) -> String {
    switch classified.stubKind(for: name) {
    case .integer: return "integer"
    case .real:    return "real"
    }
  }

  /// One stub element per column. Integer index columns get `1`
  /// (Stan's `<lower=1>` bound); other integer columns and real
  /// columns get `0` / `0.0`.
  private func stubValue(for column: String) -> String {
    if classified.indexColumns.contains(column) { return "1" }
    switch classified.stubKind(for: column) {
    case .integer: return "0"
    case .real:    return "0.0"
    }
  }

  // MARK: - Model block

  private func appendModelBlock(_ s: inout String) {
    s += "    let model = UlamModel(data: data) {\n"
    for (i, stmt) in classified.statements.enumerated() {
      let spacer = i == 0 ? "" : ""
      _ = spacer
      switch stmt.kind {
      case .likelihood:
        s += "      Likelihood(\"\(stmt.name)\", \(renderDist(stmt.dist!)))\n"
      case .link(let fn):
        s += "      Link(.\(fn.dslCase), lhs: \"\(stmt.name)\", rhs: \"\(renderLinkRhs(stmt.linkRhs!))\")\n"
      case .deterministic:
        // Bare `<name> <- <rhs>` → `Deterministic("<name>", "<rhs>")`.
        s += "      Deterministic(\"\(stmt.name)\", \"\(renderLinkRhs(stmt.linkRhs!))\")\n"
      case .scalarPrior:
        let trunc = renderTruncation(stmt.truncation)
        let constr = renderConstraints(stmt.constraints)
        s += "      Prior(\"\(stmt.name)\", \(renderDist(stmt.dist!))\(trunc)\(constr))\n"
      case .varyingPrior(let indexedBy):
        let trunc = renderTruncation(stmt.truncation)
        s += "      VaryingPrior(\"\(stmt.name)\", indexedBy: \"\(indexedBy)\", \(renderDist(stmt.dist!))\(trunc))\n"
      case .vectorPrior(let length):
        let trunc = renderTruncation(stmt.truncation)
        s += "      VectorPrior(\"\(stmt.name)\", length: \"\(length)\", \(renderDist(stmt.dist!))\(trunc))\n"
      case .varyingVectorPrior(let indexedBy, let length):
        let trunc = renderTruncation(stmt.truncation)
        s += "      VaryingVectorPrior(\"\(stmt.name)\", indexedBy: \"\(indexedBy)\", length: \"\(length)\", \(renderDist(stmt.dist!))\(trunc))\n"
      case .lkjCorrCholeskyPrior(let dim):
        // Pull eta straight from the lowered Distribution; truncation
        // is not meaningful on a cholesky_factor_corr parameter.
        if case .lkjCorrCholesky(let eta) = stmt.dist! {
          s += "      LKJCorrCholeskyPrior(\"\(stmt.name)\", dim: \"\(dim)\", eta: \(renderArg(eta)))\n"
        }
      case .generatedQuantity:
        // No Swift DSL node yet — emit a comment so the smoke driver
        // still compiles; the stancode path handles GQ emission in-process.
        s += "      // generated quantity: \(stmt.name) = \(renderDist(stmt.dist!))_rng\n"
      }
    }
    s += "    }\n"
  }

  private func renderDist(_ d: Distribution) -> String {
    switch d {
    case .normal(let mu, let sigma):
      return ".normal(\(renderArg(mu)), \(renderArg(sigma)))"
    case .bernoulli(let p):
      return ".bernoulli(p: \(renderArg(p)))"
    case .binomial(let n, let p):
      return ".binomial(n: \(renderArg(n)), p: \(renderArg(p)))"
    case .beta(let a, let b):
      return ".beta(\(renderArg(a)), \(renderArg(b)))"
    case .exponential(let rate):
      return ".exponential(\(renderArg(rate)))"
    case .poisson(let r):
      return ".poisson(\(renderArg(r)))"
    case .gamma(let a, let b):
      return ".gamma(\(renderArg(a)), \(renderArg(b)))"
    case .cauchy(let mu, let sigma):
      return ".cauchy(\(renderArg(mu)), \(renderArg(sigma)))"
    case .lognormal(let mu, let sigma):
      return ".lognormal(\(renderArg(mu)), \(renderArg(sigma)))"
    case .uniform(let lo, let hi):
      return ".uniform(lower: \(renderArg(lo)), upper: \(renderArg(hi)))"
    case .studentT(let nu, let mu, let sigma):
      return ".studentT(nu: \(renderArg(nu)), mu: \(renderArg(mu)), sigma: \(renderArg(sigma)))"
    case .multivariateNormal(let mu, let sigma):
      return ".multivariateNormal(mu: \(renderArg(mu)), sigma: \(renderArg(sigma)))"
    case .lkjCorrCholesky(let eta):
      return ".lkjCorrCholesky(\(renderArg(eta)))"
    case .multivariateNormalCholesky(let mean, let chol):
      return ".multivariateNormalCholesky(mean: \(renderArg(mean)), chol: \(renderArg(chol)))"
    case .wishart(let nu, let V):
      return ".wishart(nu: \(renderArg(nu)), V: \(renderArg(V)))"
    case .orderedLogistic(let eta, let cp):
      return ".orderedLogistic(eta: \(renderArg(eta)), cutpoints: \(renderArg(cp)))"
    case .orderedProbit(let eta, let cp):
      return ".orderedProbit(eta: \(renderArg(eta)), cutpoints: \(renderArg(cp)))"
    case .dirichlet(let alpha):
      return ".dirichlet(\(renderArg(alpha)))"
    }
  }

  private func renderArg(_ a: DistributionArg) -> String {
    switch a {
    case .literal(let v):
      if v == v.rounded(), abs(v) < 1e15 {
        return "\(Int(v))"
      }
      return "\(v)"
    case .symbol(let n):
      return "\"\(n)\""
    case .expression(let s):
      // Compound expression — render as `.expression("…")` rather than
      // the bare string literal so round-tripping through `dsl2stan`
      // preserves the semantic distinction (string-literal init goes
      // to `.symbol`, which would mis-classify the embedded
      // identifiers in `symbolsReferenced`).
      return ".expression(\"\(s)\")"
    }
  }

  private func renderTruncation(_ t: Truncation) -> String {
    if t.isEmpty { return "" }
    var inner: [String] = []
    if let lo = t.lower { inner.append("lower: \(renderArg(lo))") }
    if let hi = t.upper { inner.append("upper: \(renderArg(hi))") }
    return ", truncation: Truncation(\(inner.joined(separator: ", ")))"
  }

  private func renderConstraints(_ c: Constraints) -> String {
    if c.isEmpty { return "" }
    var inner: [String] = []
    if let lo = c.lower { inner.append("lower: \(renderArg(lo))") }
    if let hi = c.upper { inner.append("upper: \(renderArg(hi))") }
    return ", constraints: Constraints(\(inner.joined(separator: ", ")))"
  }

  private func renderLinkRhs(_ node: ExpressionNode) -> String {
    // For Q3 we'd preserve the original source whitespace, but the
    // parser already discarded it. Emit a canonical form by walking
    // the AST.
    return AlistEmitter.canonicalExpression(node)
  }

  static func canonicalExpression(_ node: ExpressionNode) -> String {
    switch node {
    case .identifier(let name): return name
    case .literal(.integer(let n)): return String(n)
    case .literal(.float(let d)): return String(d)
    case .indexed(let name, let idx):
      return "\(name)[\(canonicalExpression(idx))]"
    case .binary(let op, let l, let r):
      let ls = canonicalExpression(l)
      let rs = canonicalExpression(r)
      let lp = needsParens(child: l, parent: op)
      let rp = needsParens(child: r, parent: op)
      let lw = lp ? "(\(ls))" : ls
      let rw = rp ? "(\(rs))" : rs
      switch op {
      case .add:      return "\(lw) + \(rw)"
      case .subtract: return "\(lw) - \(rw)"
      case .multiply: return "\(lw)*\(rw)"
      case .divide:   return "\(lw)/\(rw)"
      }
    case .unary(.negate, let op):
      return "-\(canonicalExpression(op))"
    case .call(let name, let arg):
      return "\(name)(\(canonicalExpression(arg)))"
    case .chainedIndexed(let name, let outer, let inner):
      return "\(name)[\(canonicalExpression(outer))][\(canonicalExpression(inner))]"
    case .subscript2(let name, let idx1, let idx2):
      return "\(name)[\(canonicalExpression(idx1)), \(canonicalExpression(idx2))]"
    }
  }

  private static func needsParens(child: ExpressionNode, parent: BinaryOp) -> Bool {
    guard case .binary(let cop, _, _) = child else { return false }
    let pp: (BinaryOp) -> Int = { op in
      switch op {
      case .add, .subtract: return 1
      case .multiply, .divide: return 2
      }
    }
    return pp(cop) < pp(parent)
  }
}

private extension LinkFunction {
  var dslCase: String {
    switch self {
    case .logit:    return "logit"
    case .log:      return "log"
    case .invLogit: return "invLogit"
    }
  }
}
