// Chimpanzees.ulam.swift
//
// Generated by `stan alist2dsl` from `chimpanzees.alist.R`.
// Edit `chimpanzees.alist.R` and re-run `stan alist2dsl` to regenerate.
// The `data` literal carries one stub row per column — actual values
// come from `Preliminaries/chimpanzees.csv` via `csv2json`.

@main
struct ChimpanzeesSmoke {
  static func main() {
    let data: UlamData = [
      "pulled_left": .integer([0]),
      "actor": .integer([1]),
      "block_id": .integer([1]),
      "condition": .real([0.0]),
      "p": .real([0.0]),
      "prosoc_left": .real([0.0]),
    ]

    let model = UlamModel(data: data) {
      Likelihood("pulled_left", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a + a_actor[actor] + a_block[block_id] + (bp + bpc*condition)*prosoc_left")
      VaryingPrior("a_actor", indexedBy: "actor", .normal(0, "sigma_actor"))
      VaryingPrior("a_block", indexedBy: "block_id", .normal(0, "sigma_block"))
      Prior("a", .normal(0, 10))
      Prior("bp", .normal(0, 10))
      Prior("bpc", .normal(0, 10))
      Prior("sigma_actor", .cauchy(0, 1), truncation: Truncation(lower: 0))
      Prior("sigma_block", .cauchy(0, 1), truncation: Truncation(lower: 0))
    }

    do {
      print(try stancode(model))
      let inits = try stanInits(model)
      if !inits.isEmpty {
        print("// === SWIFTSTAN_INITS ===")
        print(inits)
      }
    } catch {
      print("ERROR: \(error)")
    }
  }
}
