//
//  UlamGeneratorTests.swift
//  StanTests
//
//  Golden-file tests for the pure Ulam generator (`stancode(_:)`).
//  These nail down the Phase 1–4 emission shape so Phase 5+ refactors
//  can't silently change Bernoulli/Poisson/Binomial output. Models
//  here mirror the built-in demos in `SwiftStan.Ulam.{bernoulli,poisson,
//  binomial}Demo()` — keep them in sync when the demo factories evolve.
//

import Foundation
import Testing
@testable import SwiftStan

@Suite("Ulam generator golden tests", .enabled(if: ProcessInfo.processInfo.environment["CMDSTAN"] != nil, "Set $CMDSTAN to run integration tests"))
struct UlamGeneratorTests {
  init() { _ = TestCaseRootBootstrap.install }


  // MARK: - Bernoulli + logit (canonical Statistical Rethinking opener)

  @Test func bernoulliMatchesGolden() throws {
    let data: UlamData = [
      "y": .integer([0, 1, 0, 1, 1, 0, 1, 1, 1, 0]),
      "x": .real([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a + b*x")
      Prior("a", .normal(0, 1.5))
      Prior("b", .normal(0, 0.5))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      vector[N] x;
      array[N] int<lower=0, upper=1> y;
    }
    parameters {
      real a;
      real b;
    }
    model {
      vector[N] p;
      p = inv_logit(a + b*x);
      a ~ normal(0, 1.5);
      b ~ normal(0, 0.5);
      y ~ bernoulli(p);
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Poisson + log + lpmf form (Phase 3 features)

  @Test func poissonMatchesGolden() throws {
    let data: UlamData = [
      "y": .integer([2, 1, 3, 5, 4, 6, 8, 7]),
      "x": .real([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .poisson("lambda"), useLpdf: true)
      Link(.log, lhs: "lambda", rhs: "a + b*x")
      Prior("a", .normal(0, 1.5))
      Prior("b", .cauchy(0, 1))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      vector[N] x;
      array[N] int<lower=0> y;
    }
    parameters {
      real a;
      real b;
    }
    model {
      vector[N] lambda;
      lambda = exp(a + b*x);
      a ~ normal(0, 1.5);
      b ~ cauchy(0, 1);
      target += poisson_lpmf(y | lambda);
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Binomial + logit + truncated half-normal (Phases 3+4)

  @Test func binomialMatchesGolden() throws {
    let data: UlamData = [
      "successes": .integer([2, 3, 1, 4, 5, 6, 7, 8]),
      "trials":    .integer([5, 5, 5, 5, 10, 10, 10, 10]),
      "x":         .real([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("successes", .binomial(n: "trials", p: "theta"))
      Link(.logit, lhs: "theta", rhs: "a + b*x")
      Prior("a", .normal(0, 1.5))
      Prior("b", .normal(0, 1), truncation: Truncation(lower: 0))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      array[N] int<lower=0> successes;
      array[N] int trials;
      vector[N] x;
    }
    transformed data {
      for (i in 1:N) {
        if (successes[i] > trials[i]) {
          reject("successes[", i, "] = ", successes[i],
                 " > trials[", i, "] = ", trials[i],
                 " — binomial outcome must satisfy y[i] <= trials[i]");
        }
      }
    }
    parameters {
      real a;
      real<lower=0> b;
    }
    model {
      vector[N] theta;
      theta = inv_logit(a + b*x);
      a ~ normal(0, 1.5);
      b ~ normal(0, 1) T[0, ];
      successes ~ binomial(trials, theta);
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Binomial outcome bounds (2026-06-06, TODO §2)

  /// Literal `n` (`binomial(.literal(10), p)`) tightens the outcome
  /// declaration to `<lower=0, upper=10>` and skips the per-row
  /// transformed-data check — Stan rejects out-of-range values at the
  /// declaration site with a stock data-validation error that's already
  /// row-localised.
  @Test func binomialLiteralTrialsTightensDeclarationBound() throws {
    let data: UlamData = [
      "y": .integer([2, 3, 1, 4, 5, 6, 7, 8]),
      "x": .real([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .binomial(n: 10, p: "theta"))
      Link(.logit, lhs: "theta", rhs: "a + b*x")
      Prior("a", .normal(0, 1.5))
      Prior("b", .normal(0, 1))
    }
    let stan = try stancode(model)
    #expect(stan.contains("array[N] int<lower=0, upper=10> y;"),
            "literal trials should tighten declaration to <upper=10>")
    #expect(!stan.contains("transformed data"),
            "literal trials skip the row-loop check")
  }

  /// `.scalarInt` data entry as `n` (`binomial(.symbol("N_trials"), p)`
  /// with `"N_trials": .scalarInt(20)`) tightens the declaration to
  /// `<lower=0, upper=N_trials>` and skips the per-row loop, same as
  /// literal n.
  @Test func binomialScalarIntTrialsTightensDeclarationBound() throws {
    let data: UlamData = [
      "y":        .integer([2, 3, 1, 4, 5]),
      "x":        .real([0.1, 0.2, 0.3, 0.4, 0.5]),
      "N_trials": .scalarInt(20),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .binomial(n: "N_trials", p: "theta"))
      Link(.logit, lhs: "theta", rhs: "a + b*x")
      Prior("a", .normal(0, 1.5))
      Prior("b", .normal(0, 1))
    }
    let stan = try stancode(model)
    #expect(stan.contains("array[N] int<lower=0, upper=N_trials> y;"),
            "scalarInt trials should tighten declaration to <upper=N_trials>")
    #expect(!stan.contains("transformed data"),
            "scalarInt trials skip the row-loop check")
  }

  /// Regression guard for the no-binomial case: a Bernoulli-only model
  /// should NOT emit a `transformed data {}` block. The
  /// `transformedDataBlock(_:)` returns nil and `assemble` skips it.
  @Test func nonBinomialModelOmitsTransformedDataBlock() throws {
    let data: UlamData = [
      "y": .integer([0, 1, 0, 1]),
      "x": .real([0.1, 0.2, 0.3, 0.4]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a + b*x")
      Prior("a", .normal(0, 1.5))
      Prior("b", .normal(0, 1))
    }
    let stan = try stancode(model)
    #expect(!stan.contains("transformed data"),
            "non-binomial models shouldn't emit transformed data")
  }

  // MARK: - DistributionArg.expression (2026-06-08, TestResults §2)

  /// `.expression("…")` in a distribution-arg slot renders verbatim
  /// into the emitted Stan source — the linear predictor goes straight
  /// into the `~` line without being lifted to a separate `mu = …;`
  /// assignment. The tokenised identifiers (`alpha`, `beta`, `x`) all
  /// flow into the data block via `symbolsReferenced`.
  @Test func distributionArgExpressionEmitsVerbatim() throws {
    let data: UlamData = [
      "y": .real([0.1, 0.2, 0.3, 0.4]),
      "x": .real([1.0, 2.0, 3.0, 4.0]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .normal(.expression("alpha + beta*x"), "sigma"))
      Prior("alpha", .normal(0, 10))
      Prior("beta", .normal(0, 10))
      Prior("sigma", .normal(0, 10), truncation: Truncation(lower: 0))
    }
    let stan = try stancode(model)
    // Verbatim emission: the `alpha + beta*x` source appears as the
    // mu arg of `normal(...)` directly.
    #expect(stan.contains("y ~ normal(alpha + beta*x, sigma);"),
            "expected verbatim expression in the sampling line; got:\n\(stan)")
    // Identifiers from the expression were harvested into the parameter
    // / data declaration sets (alpha + beta were declared via Prior →
    // they're parameters; the expression-tokeniser keeps them off the
    // data block).
    #expect(stan.contains("real alpha;"))
    #expect(stan.contains("real beta;"))
    #expect(stan.contains("vector[N] x;"),
            "expected `x` from the expression to land as data")
  }

  /// Round-trip the alist-1 shape (`dnorm(<expr>, sigma)`) through the
  /// DSL directly to confirm the new lowering path produces Stan whose
  /// data block declares the index column. The alist-side end-to-end
  /// (parsing the .alist.R fixture) needs a CSV with `county` data —
  /// that's `csv2json` territory and out of scope here.
  @Test func expressionArgWithIndexedReferenceEmitsIndexColumn() throws {
    let data: UlamData = [
      "log_radon": .real([1.1, 1.2, 1.3, 1.4]),
      "county":    .integer([1, 2, 1, 2]),
      "floor":     .real([0, 1, 0, 1]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("log_radon",
                 .normal(.expression("alpha[county] + beta*floor"), "sigma"))
      VaryingPrior("alpha", indexedBy: "county", .normal(0, 10))
      Prior("beta", .normal(0, 10))
      Prior("sigma", .normal(0, 10), truncation: Truncation(lower: 0))
    }
    let stan = try stancode(model)
    #expect(stan.contains("array[N] int<lower=1, upper=N_county> county;"),
            "expected county to be declared as an index column")
    #expect(stan.contains("vector[N_county] alpha;"),
            "expected alpha to be a vector parameter keyed on county")
    #expect(stan.contains("log_radon ~ normal(alpha[county] + beta*floor, sigma);"),
            "expected verbatim indexed expression on the sampling line; got:\n\(stan)")
  }

  // MARK: - Phase 4 error paths

  @Test func truncationWithLpdfIsRejected() throws {
    let model = UlamModel(data: ["y": .real([1.0, 2.0])]) {
      Likelihood("y", .normal(0, 1),
                 truncation: Truncation(lower: 0),
                 useLpdf: true)
    }
    #expect(throws: BlockEmitterError.self) {
      _ = try stancode(model)
    }
  }

  @Test func conflictingParameterConstraintsAreRejected() throws {
    let model = UlamModel(data: ["y": .real([1.0])]) {
      Likelihood("y", .normal("mu", 1))
      Prior("mu", .normal(0, 1), truncation: Truncation(lower: 0))
      Prior("mu", .normal(0, 1), truncation: Truncation(upper: 1))
    }
    #expect(throws: DataInferenceError.self) {
      _ = try stancode(model)
    }
  }

  // MARK: - Phase 5 multilevel goldens

  /// Canonical varying-intercept Bernoulli — the Statistical Rethinking
  /// chapter-13 opener as a Stan port target.
  @Test func multilevelBernoulliMatchesGolden() throws {
    let data: UlamData = [
      "y":     .integer([0, 1, 0, 1, 1, 0, 1, 1]),
      "x":     .real([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]),
      "group": .integer([1, 2, 1, 2, 1, 2, 1, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a[group] + b*x")
      VaryingPrior("a", indexedBy: "group", .normal("a_bar", "sigma_a"))
      Prior("a_bar", .normal(0, 1.5))
      Prior("sigma_a", .exponential(1))
      Prior("b", .normal(0, 0.5))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      int<lower=1> N_group;
      array[N] int<lower=1, upper=N_group> group;
      vector[N] x;
      array[N] int<lower=0, upper=1> y;
    }
    parameters {
      vector[N_group] a;
      real a_bar;
      real sigma_a;
      real b;
    }
    model {
      vector[N] p;
      p = inv_logit(a[group] + b*x);
      a ~ normal(a_bar, sigma_a);
      a_bar ~ normal(0, 1.5);
      sigma_a ~ exponential(1);
      b ~ normal(0, 0.5);
      y ~ bernoulli(p);
    }
    """

    #expect(try stancode(model) == expected)
  }

  /// UCB Berkeley admissions (varying-intercept binomial logistic regression)
  /// — mirrors `~/Documents/StanCases/UCB/UCB.mcelreath.R`. Exercises
  /// the `countSymbol:` override too: we use `K` instead of `N_dept`.
  @Test func ucbBinomialWithCountSymbolOverride() throws {
    let data: UlamData = [
      "admit":        .integer([512, 89, 353, 17, 120, 202, 138, 131, 53, 94, 22, 24]),
      "applications": .integer([825, 108, 560, 25, 325, 593, 417, 375, 191, 393, 373, 341]),
      "male":         .real([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]),
      "dept":         .integer([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("admit", .binomial(n: "applications", p: "p"))
      Link(.logit, lhs: "p", rhs: "a[dept] + b*male")
      VaryingPrior("a", indexedBy: "dept",
                   .normal("abar", "sigma"),
                   countSymbol: "K")
      Prior("abar", .normal(0, 4))
      Prior("sigma", .normal(0, 1), truncation: Truncation(lower: 0))
      Prior("b", .normal(0, 1))
    }

    let stan = try stancode(model)
    // Spot-check the key Phase 5 features rather than a 25-line golden:
    #expect(stan.contains("int<lower=1> K;"))
    #expect(stan.contains("array[N] int<lower=1, upper=K> dept;"))
    #expect(stan.contains("vector[K] a;"))
    #expect(stan.contains("real<lower=0> sigma;"))
    #expect(stan.contains("a ~ normal(abar, sigma);"))
    #expect(stan.contains("p = inv_logit(a[dept] + b*male);"))
    #expect(stan.contains("admit ~ binomial(applications, p);"))
    // The custom countSymbol means the auto-derived "N_dept" never appears.
    #expect(!stan.contains("N_dept"))
  }

  // MARK: - Phase 6 multivariate-normal goldens

  /// Bivariate-mean estimation — the canonical option-3 Phase-6 demo.
  /// Verifies cardinality-symbol binding (`K` ↔ length 2), the new
  /// data declarations (`vector[K] zero;`, `cov_matrix[K] Sigma_*;`,
  /// `array[N] vector[K] y;`), the vector parameter (`vector[K] mu;`),
  /// and `multi_normal(...)` rendering.
  @Test func dmvnormBivariateMatchesGolden() throws {
    let data: UlamData = [
      "y":           .realArrayVector(rowCount: 4, colCount: 2,
                                      values: [[1.1, 0.4], [0.9, 0.6],
                                               [1.0, 0.5], [1.2, 0.3]]),
      "zero":        .realVector(length: 2, values: [0, 0]),
      "Sigma_prior": .realCovMatrix(dim: 2, values: [[1, 0.5], [0.5, 1]]),
      "Sigma_obs":   .realCovMatrix(dim: 2, values: [[0.2, 0.05], [0.05, 0.2]]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .multivariateNormal(mu: "mu", sigma: "Sigma_obs"))
      VectorPrior("mu", length: "K",
                  .multivariateNormal(mu: "zero", sigma: "Sigma_prior"))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      int<lower=1> K;
      array[N] vector[K] y;
      cov_matrix[K] Sigma_obs;
      cov_matrix[K] Sigma_prior;
      vector[K] zero;
    }
    parameters {
      vector[K] mu;
    }
    model {
      mu ~ multi_normal(zero, Sigma_prior);
      y ~ multi_normal(mu, Sigma_obs);
    }
    """

    #expect(try stancode(model) == expected)
  }

  @Test func multivariateTruncationIsRejected() throws {
    let data: UlamData = [
      "zero":  .realVector(length: 2, values: [0, 0]),
      "Sigma": .realCovMatrix(dim: 2, values: [[1, 0], [0, 1]]),
    ]
    let model = UlamModel(data: data) {
      VectorPrior("mu", length: "K",
                  .multivariateNormal(mu: "zero", sigma: "Sigma"),
                  truncation: Truncation(lower: 0))
    }
    #expect(throws: DataInferenceError.self) {
      _ = try stancode(model)
    }
  }

  @Test func vectorPriorWithoutAnchoringColumnRejected() throws {
    // No realVector / realCovMatrix / realArrayVector exists, so `K`
    // is unbound.
    let data: UlamData = ["y": .real([1.0, 2.0])]
    let model = UlamModel(data: data) {
      Likelihood("y", .normal("mu", 1))
      VectorPrior("mu", length: "K", .normal(0, 1))
    }
    #expect(throws: DataInferenceError.self) {
      _ = try stancode(model)
    }
  }

  @Test func scalarAndVaryingPriorOnSameSymbolRejected() throws {
    let model = UlamModel(data: [
      "y":     .real([1.0]),
      "group": .integer([1]),
    ]) {
      Likelihood("y", .normal("a", 1))
      Prior("a", .normal(0, 1))
      VaryingPrior("a", indexedBy: "group", .normal(0, 1))
    }
    #expect(throws: DataInferenceError.self) {
      _ = try stancode(model)
    }
  }

  @Test func loopEmissionRequiredForIndexedRhs() throws {
    let data: UlamData = [
      "y":     .integer([0, 1, 0, 1]),
      "x":     .real([0.1, 0.2, 0.3, 0.4]),
      "group": .integer([1, 2, 1, 2]),
    ]
    // Until Phase 5 declares `a` as a vector parameter indexed by
    // `group`, a Link RHS containing `a[group]` routes to the
    // loop-emission stub.
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a[group] + b*x")
      Prior("a", .normal(0, 1.5))
      Prior("b", .normal(0, 0.5))
    }
    #expect(throws: BlockEmitterError.self) {
      _ = try stancode(model)
    }
  }

  // MARK: - Phase 5.5 Slice B: parser-backed vectorisation strategy

  /// Parenthesised RHS with no indexing should still vectorise. The
  /// Phase 4 regex didn't break on this (it just didn't see the parens),
  /// but the parser-based strategy needs to handle parens correctly.
  @Test func parensWithoutIndexingStillVectorise() throws {
    let data: UlamData = [
      "y": .integer([0, 1, 0, 1]),
      "x": .real([0.1, 0.2, 0.3, 0.4]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "(a + b)*x")
      Prior("a", .normal(0, 1.5))
      Prior("b", .normal(0, 0.5))
    }
    let stan = try stancode(model)
    #expect(stan.contains("p = inv_logit((a + b)*x);"))
  }

  /// Whitespace inside an indexed reference (`a [ group ]`) is invisible
  /// to the old regex but the parser sees the indexing structurally.
  /// Since `a` here is a scalar `Prior` (not a vector parameter), the
  /// parser-based strategy correctly throws `loopEmissionRequired`
  /// rather than silently vectorising an ill-typed Stan model.
  @Test func whitespaceDisguisedIndexingTriggersLoopEmission() throws {
    let data: UlamData = [
      "y":     .integer([0, 1, 0, 1]),
      "x":     .real([0.1, 0.2, 0.3, 0.4]),
      "group": .integer([1, 2, 1, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a [ group ] + b*x")
      Prior("a", .normal(0, 1.5))   // scalar — not a VaryingPrior
      Prior("b", .normal(0, 0.5))
    }
    #expect(throws: BlockEmitterError.self) {
      _ = try stancode(model)
    }
  }

  /// Nested indexing (`a[group[i]]`) needs the loop body translation
  /// that Slice D will deliver. Slice B keeps routing it to the
  /// loop-emission stub. Tested at the classifier level (not the full
  /// `stancode()` pipeline) because `DataInference` rejects the
  /// undeclared `i` first — but the strategy walk itself is the unit
  /// under test here.
  @Test func nestedIndexingClassifiesAsLoop() throws {
    let statement = Statement.link(function: .logit,
                                   lhs: "p",
                                   rhs: Expression("a[group[i]] + b*x"))
    let strategy = try BlockEmitter.vectorisationStrategy(
      for: statement,
      knownVectorParameters: ["a"],
      knownIndexColumns: ["group"])
    #expect(strategy == .loop)
  }

  // MARK: - Phase 5.5 Slice C: int-column auto-promotion

  /// UCB demo with raw integer `male` predictor: the inference pass
  /// detects `b*male` and promotes `male` from `array[N] int male;`
  /// to `vector[N] male;` so Stan's real-typed arithmetic accepts it.
  /// This replaces the pre-Slice-C workaround of declaring `male` as
  /// `.real(...)` up front.
  @Test func ucbWithIntegerMaleAutoPromotesToVector() throws {
    let data: UlamData = [
      "admit":        .integer([512, 89, 353, 17, 120, 202, 138, 131, 53, 94, 22, 24]),
      "applications": .integer([825, 108, 560, 25, 325, 593, 417, 375, 191, 393, 373, 341]),
      "male":         .integer([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]),
      "dept":         .integer([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("admit", .binomial(n: "applications", p: "p"))
      Link(.logit, lhs: "p", rhs: "a[dept] + b*male")
      VaryingPrior("a", indexedBy: "dept", .normal("abar", "sigma"))
      Prior("abar", .normal(0, 4))
      Prior("sigma", .normal(0, 1), truncation: Truncation(lower: 0))
      Prior("b", .normal(0, 1))
    }
    let stan = try stancode(model)
    #expect(stan.contains("vector[N] male;"))
    #expect(!stan.contains("array[N] int male"))
    // Other int columns must not be promoted: `dept` is the inner part
    // of `a[dept]` so it stays an indexed int column, and `admit` /
    // `applications` aren't multiplicative operands.
    #expect(stan.contains("array[N] int<lower=1, upper=N_dept> dept;"))
    #expect(stan.contains("array[N] int<lower=0> admit;"))
    #expect(stan.contains("array[N] int applications;"))
  }

  /// Index columns must NOT be promoted even if they appear in
  /// arithmetic — Stan requires `array[N] int` for array subscripts.
  /// This is a defensive test: under normal use, an index column
  /// referenced as `a[group]` wouldn't surface as a multiplicative
  /// operand, but if a contrived RHS did both (e.g. `a[group] + 2*group`)
  /// the index-column declaration must win.
  @Test func indexColumnsAreNotAutoPromotedEvenWhenMultiplicativeOperand() throws {
    let data: UlamData = [
      "y":     .integer([0, 1, 0, 1]),
      "x":     .real([0.1, 0.2, 0.3, 0.4]),
      "group": .integer([1, 2, 1, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a[group] + b*x + 2*group")
      VaryingPrior("a", indexedBy: "group", .normal("a_bar", "sigma_a"))
      Prior("a_bar", .normal(0, 1.5))
      Prior("sigma_a", .exponential(1))
      Prior("b", .normal(0, 0.5))
    }
    let stan = try stancode(model)
    // `group` must remain an integer array because it's an index column.
    #expect(stan.contains("array[N] int<lower=1, upper=N_group> group;"))
    #expect(!stan.contains("vector[N] group;"))
  }

  /// An unparseable RHS now surfaces as
  /// `BlockEmitterError.malformedExpression` instead of silently
  /// vectorising whatever the regex happened to (not) match.
  @Test func malformedRhsThrowsMalformedExpressionError() throws {
    let data: UlamData = [
      "y": .integer([0, 1, 0, 1]),
      "x": .real([0.1, 0.2, 0.3, 0.4]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a + + b")
      Prior("a", .normal(0, 1.5))
      Prior("b", .normal(0, 0.5))
    }
    #expect(throws: BlockEmitterError.self) {
      _ = try stancode(model)
    }
  }

  // MARK: - Phase 5.5 Slice E: non-centred parameterisation

  /// `VaryingPrior(..., nonCentered: true)` emits the Matt Trick form:
  /// `a_raw ~ std_normal();` in the model block, and a
  /// `transformed parameters {}` block that defines
  /// `a = a_bar + sigma_a * a_raw;`. The centred multilevel Bernoulli
  /// golden (`multilevelBernoulliMatchesGolden` above) still passes
  /// byte-identically, confirming the change is opt-in.
  @Test func multilevelBernoulliNonCentredMatchesGolden() throws {
    let data: UlamData = [
      "y":     .integer([0, 1, 0, 1, 1, 0, 1, 1]),
      "x":     .real([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]),
      "group": .integer([1, 2, 1, 2, 1, 2, 1, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a[group] + b*x")
      VaryingPrior("a", indexedBy: "group",
                   .normal("a_bar", "sigma_a"),
                   nonCentered: true)
      Prior("a_bar", .normal(0, 1.5))
      Prior("sigma_a", .exponential(1))
      Prior("b", .normal(0, 0.5))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      int<lower=1> N_group;
      array[N] int<lower=1, upper=N_group> group;
      vector[N] x;
      array[N] int<lower=0, upper=1> y;
    }
    parameters {
      vector[N_group] a_raw;
      real a_bar;
      real sigma_a;
      real b;
    }
    transformed parameters {
      vector[N_group] a;
      a = a_bar + sigma_a * a_raw;
    }
    model {
      vector[N] p;
      p = inv_logit(a[group] + b*x);
      a_raw ~ std_normal();
      a_bar ~ normal(0, 1.5);
      sigma_a ~ exponential(1);
      b ~ normal(0, 0.5);
      y ~ bernoulli(p);
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Gaussian process priors (McElreath Chapter 14 oceanic tools)

  /// Mini oceanic-tools shape: 5 islands, Poisson outcome, GP over a
  /// pre-computed `Dmat` distance matrix with hyperparameters
  /// `etasq` / `rhosq` and the canonical 0.01 diagonal jitter.
  /// `Dmat` enters as `matrix[N, N]` (square), driven by the GP node
  /// marking it as a square data column.
  @Test func gaussianProcessOceanicMatchesGolden() throws {
    let dmat: [[Double]] = [
      [0.0, 1.0, 2.0, 3.0, 4.0],
      [1.0, 0.0, 1.5, 2.5, 3.5],
      [2.0, 1.5, 0.0, 1.0, 2.0],
      [3.0, 2.5, 1.0, 0.0, 1.5],
      [4.0, 3.5, 2.0, 1.5, 0.0],
    ]
    let data: UlamData = [
      "T":       .integer([3, 5, 8, 10, 12]),
      "P":       .real([1.0, 2.0, 3.0, 4.0, 5.0]),
      "society": .integer([1, 2, 3, 4, 5]),
      "Dmat":    .realMatrix(rows: 5, cols: 5, values: dmat),
    ]
    let model = UlamModel(data: data) {
      Likelihood("T", .poisson("lambda"))
      Link(.log, lhs: "lambda", rhs: "a + g[society] + b*P")
      GaussianProcessPrior("g", indexedBy: "society",
                           distanceMatrix: "Dmat",
                           etasq: "etasq", rhosq: "rhosq")
      Prior("a", .normal(0, 1))
      Prior("b", .normal(0, 0.5))
      Prior("etasq", .exponential(2), truncation: Truncation(lower: 0))
      Prior("rhosq", .exponential(0.5), truncation: Truncation(lower: 0))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      matrix[N, N] Dmat;
      vector[N] P;
      array[N] int<lower=0> T;
      array[N] int<lower=1, upper=N> society;
    }
    parameters {
      vector[N] g_z;
      real a;
      real b;
      real<lower=0> etasq;
      real<lower=0> rhosq;
    }
    transformed parameters {
      vector[N] g;
      {
        matrix[N, N] K;
        for (i in 1:N) {
          for (j in 1:N) {
            K[i, j] = etasq * exp(-rhosq * square(Dmat[i, j]));
          }
          K[i, i] = K[i, i] + 0.01;
        }
        g = cholesky_decompose(K) * g_z;
      }
    }
    model {
      vector[N] lambda;
      lambda = exp(a + g[society] + b*P);
      g_z ~ std_normal();
      a ~ normal(0, 1);
      b ~ normal(0, 0.5);
      etasq ~ exponential(2) T[0, ];
      rhosq ~ exponential(0.5) T[0, ];
      T ~ poisson(lambda);
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Ordered logit / probit (McElreath Chapter 12 Trolley shape)

  /// Mini Trolley-style ordered-logit model: 5 observations, 3 response
  /// categories, three binary predictors entering a linear predictor
  /// `phi`. Exercises the declaration-only `OrderedCutpoints` node,
  /// `int<lower=1, upper=K>` outcome bounds derived from the
  /// `cutpoints` arg's K binding, and Stan's vectorisation of a scalar
  /// normal prior over the K-1 cutpoints.
  @Test func orderedLogitMatchesGolden() throws {
    let data: UlamData = [
      "K":         .scalarInt(3),
      "R":         .integer([1, 2, 3, 2, 1]),
      "action":    .integer([0, 1, 0, 1, 0]),
      "contact":   .integer([1, 0, 0, 1, 1]),
      "intention": .integer([1, 1, 0, 0, 1]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("R", .orderedLogistic(eta: "phi", cutpoints: "cutpoints"))
      Deterministic("phi", "bA*action + bC*contact + bI*intention")
      Prior("bA", .normal(0, 0.5))
      Prior("bC", .normal(0, 0.5))
      Prior("bI", .normal(0, 0.5))
      OrderedCutpoints("cutpoints", K: "K")
      Prior("cutpoints", .normal(0, 1.5))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      array[N] int<lower=1, upper=K> R;
      vector[N] action;
      vector[N] contact;
      vector[N] intention;
      int K;
    }
    parameters {
      real bA;
      real bC;
      real bI;
      ordered[K-1] cutpoints;
    }
    model {
      vector[N] phi;
      phi = bA*action + bC*contact + bI*intention;
      bA ~ normal(0, 0.5);
      bC ~ normal(0, 0.5);
      bI ~ normal(0, 0.5);
      cutpoints ~ normal(0, 1.5);
      R ~ ordered_logistic(phi, cutpoints);
    }
    """

    #expect(try stancode(model) == expected)
  }

  /// Probit variant — same fixture, distribution swapped to
  /// `.orderedProbit`. Asserts the catalog renders the right Stan
  /// function name and nothing else diverges.
  @Test func orderedProbitMatchesGolden() throws {
    let data: UlamData = [
      "K":         .scalarInt(3),
      "R":         .integer([1, 2, 3, 2, 1]),
      "action":    .integer([0, 1, 0, 1, 0]),
      "contact":   .integer([1, 0, 0, 1, 1]),
      "intention": .integer([1, 1, 0, 0, 1]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("R", .orderedProbit(eta: "phi", cutpoints: "cutpoints"))
      Deterministic("phi", "bA*action + bC*contact + bI*intention")
      Prior("bA", .normal(0, 0.5))
      Prior("bC", .normal(0, 0.5))
      Prior("bI", .normal(0, 0.5))
      OrderedCutpoints("cutpoints", K: "K")
      Prior("cutpoints", .normal(0, 1.5))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      array[N] int<lower=1, upper=K> R;
      vector[N] action;
      vector[N] contact;
      vector[N] intention;
      int K;
    }
    parameters {
      real bA;
      real bC;
      real bI;
      ordered[K-1] cutpoints;
    }
    model {
      vector[N] phi;
      phi = bA*action + bC*contact + bI*intention;
      bA ~ normal(0, 0.5);
      bC ~ normal(0, 0.5);
      bI ~ normal(0, 0.5);
      cutpoints ~ normal(0, 1.5);
      R ~ ordered_probit(phi, cutpoints);
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Monotonic effects (McElreath Chapter 12 mo() / brms)

  /// Mini monotonic-effects model: continuous Normal outcome, one
  /// continuous predictor `x`, one monotonic ordinal predictor `edu`
  /// (K_edu = 4 levels), and a Dirichlet prior on the simplex `delta`.
  /// `alpha` (the Dirichlet concentration vector) anchors the K_edu
  /// cardinality via the existing Phase-6 path — the user doesn't
  /// supply K_edu as a separate scalarInt. `MonotonicEffect` consumes
  /// the matching Deterministic and emits a single per-row for-loop
  /// that augments the base RHS with `bE * sum(delta[1:edu[i]])`.
  @Test func monotonicEffectsMatchesGolden() throws {
    let data: UlamData = [
      "y":     .real([1.0, 2.0, 3.0, 2.5, 1.5, 2.8]),
      "x":     .real([0.1, 0.3, 0.5, 0.7, 0.4, 0.6]),
      "edu":   .integer([1, 2, 3, 4, 2, 3]),
      "alpha": .realVector(length: 4, values: [2.0, 2.0, 2.0, 2.0]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .normal("mu", "sigma"))
      Deterministic("mu", "a + bX*x")
      MonotonicEffect("delta", scale: "bE", predictor: "edu",
                      levels: "K_edu", targetLhs: "mu")
      Prior("a", .normal(0, 1))
      Prior("bX", .normal(0, 1))
      Prior("bE", .normal(0, 1))
      Prior("sigma", .exponential(1), truncation: Truncation(lower: 0))
      SimplexPrior("delta", length: "K_edu")
      Prior("delta", .dirichlet("alpha"))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      int<lower=1> K_edu;
      array[N] int edu;
      vector[N] x;
      vector[N] y;
      vector[K_edu] alpha;
    }
    parameters {
      real a;
      real bX;
      real bE;
      real<lower=0> sigma;
      simplex[K_edu] delta;
    }
    model {
      vector[N] mu;
      for (i in 1:N) {
        mu[i] = a + bX*x[i] + bE * sum(delta[1:edu[i]]);
      }
      a ~ normal(0, 1);
      bX ~ normal(0, 1);
      bE ~ normal(0, 1);
      sigma ~ exponential(1) T[0, ];
      delta ~ dirichlet(alpha);
      y ~ normal(mu, sigma);
    }
    """

    #expect(try stancode(model) == expected)
  }

  /// The Matt Trick decomposition is only defined for `normal(mu, sigma)`.
  /// Asking for `nonCentered: true` with any other distribution is a
  /// model-construction error.
  @Test func nonCenteredOnNonNormalIsRejected() throws {
    let data: UlamData = [
      "y":     .integer([0, 1, 0, 1]),
      "group": .integer([1, 2, 1, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a[group]")
      // Exponential isn't a location-scale family — can't be
      // reparameterised via standard-normal shifts.
      VaryingPrior("a", indexedBy: "group",
                   .exponential(1),
                   nonCentered: true)
    }
    #expect(throws: DataInferenceError.self) {
      _ = try stancode(model)
    }
  }

  // MARK: - Phase 5.5 Slice D: loop emission body

  /// Slice D loop emission for a `Deterministic` (no inverse-link
  /// wrapping) — verifies that the dispatch path inside `modelBlock`
  /// handles both `.link` and `.deterministic` with the same shape.
  /// Tested at the classifier level since the model isn't sensible
  /// to round-trip through cmdstan as-is.
  @Test func loopEmissionForDeterministicAssignment() throws {
    let statement = Statement.deterministic(lhs: "mu",
                                            rhs: Expression("a[group]*c[year]"))
    let strategy = try BlockEmitter.vectorisationStrategy(
      for: statement,
      knownVectorParameters: ["a", "c"],
      knownIndexColumns: ["group", "year"])
    #expect(strategy == .loop)
  }

  /// Two vector parameters keyed on *different* index columns,
  /// multiplied together (`a[group] * c[year]`). Each operand alone
  /// would vectorise; the multiplication is `vector * vector` and
  /// Slice D's classifier routes it through the loop emitter. The
  /// per-row body subscripts both index columns
  /// (`a[group[i]]*c[year[i]]`).
  @Test func loopEmissionTranslatesTwoVectorMultiply() throws {
    let data: UlamData = [
      "y":     .integer([0, 1, 0, 1, 1, 0]),
      "group": .integer([1, 2, 1, 2, 1, 2]),
      "year":  .integer([1, 1, 2, 2, 3, 3]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a[group]*c[year]")
      VaryingPrior("a", indexedBy: "group", .normal("a_bar", "sigma_a"))
      VaryingPrior("c", indexedBy: "year", .normal("c_bar", "sigma_c"))
      Prior("a_bar", .normal(0, 1.5))
      Prior("sigma_a", .exponential(1))
      Prior("c_bar", .normal(0, 1.5))
      Prior("sigma_c", .exponential(1))
    }
    let stan = try stancode(model)
    #expect(stan.contains("for (i in 1:N) {"))
    #expect(stan.contains("p[i] = inv_logit(a[group[i]]*c[year[i]]);"))
    // Neither vector parameter is subscripted bare — only via its
    // index column.
    #expect(!stan.contains("p = inv_logit(a[group]*c[year]);"))
  }

  // MARK: - SUR Slices A + B: matrix and cov_matrix parameter primitives

  /// Standalone golden for the two new SUR parameter shapes — no
  /// data outcomes yet, no likelihood, just the parameter
  /// declarations and the matrix iid prior. Exercises the smallest
  /// possible model:
  ///   - `MatrixPrior("beta", rows: "K", cols: "J", .normal(0, 1))`
  ///     declares `matrix[K, J] beta;` in `parameters` and emits the
  ///     iid prior via `to_vector(beta) ~ normal(0, 1);`.
  ///   - `CovMatrixPrior("Sigma", dim: "J")` declares
  ///     `cov_matrix[J] Sigma;` — no sampling line, Stan's
  ///     positive-definite constraint is the implicit prior.
  /// `K` and `J` are bound by scalar-int data columns; Slice C will
  /// extend the binding so a matrix data column's shape can supply
  /// them automatically.
  @Test func surMatrixAndCovMatrixPrimitivesMatchGolden() throws {
    let data: UlamData = [
      "K": .scalarInt(2),
      "J": .scalarInt(3),
    ]
    let model = UlamModel(data: data) {
      MatrixPrior("beta", rows: "K", cols: "J", .normal(0, 1))
      CovMatrixPrior("Sigma", dim: "J")
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int J;
      int K;
    }
    parameters {
      matrix[K, J] beta;
      cov_matrix[J] Sigma;
    }
    model {
      to_vector(beta) ~ normal(0, 1);
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Multivariate hierarchical priors Slice A: LKJ-Cholesky

  /// Standalone golden for the cholesky_factor_corr parameter shape +
  /// the lkj_corr_cholesky prior. No data outcomes — just the
  /// declaration and the sampling line.
  ///
  /// `J` is bound by a scalar-int data column (the dimension of the
  /// correlation matrix being modelled).
  @Test func lkjCorrCholeskyPriorMatchesGolden() throws {
    let data: UlamData = [
      "J": .scalarInt(2),
    ]
    let model = UlamModel(data: data) {
      LKJCorrCholeskyPrior("L_Omega", dim: "J", eta: 2)
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int J;
    }
    parameters {
      cholesky_factor_corr[J] L_Omega;
    }
    model {
      L_Omega ~ lkj_corr_cholesky(2);
    }
    """

    #expect(try stancode(model) == expected)
  }

  @Test func wishartPriorMatchesGolden() throws {
    let data: UlamData = [
      "K":       .scalarInt(2),
      "nu":      .scalarInt(3),
      "V_scale": .realCovMatrix(dim: 2, values: [[1, 0], [0, 1]]),
    ]
    let model = UlamModel(data: data) {
      WishartPrior("Omega", dim: "K", nu: "nu", V: "V_scale")
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int K;
      cov_matrix[K] V_scale;
      int nu;
    }
    parameters {
      cov_matrix[K] Omega;
    }
    model {
      Omega ~ wishart(nu, V_scale);
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Multivariate hierarchical priors Slice C: vector-valued varying effects

  /// Probe: dump the emission for the Slices A+B+C combination so the
  /// golden below can be locked. Verifies that VaryingVectorPrior +
  /// LKJCorrCholeskyPrior + multi_normal_cholesky compose into the
  /// expected idiomatic Stan source. No data outcomes — just the
  /// parameter declarations and the multivariate sampling line.
  @Test func varyingVectorPriorMatchesGolden() throws {
    let data: UlamData = [
      "J": .scalarInt(2),
      "cafe": .integer([1, 2, 1, 2, 1, 2]),
    ]
    let model = UlamModel(data: data) {
      Prior("a_bar", .normal(0, 5))
      Prior("b_bar", .normal(0, 5))
      VectorPrior("sigma_ab", length: "J", .exponential(1),
                  truncation: Truncation(lower: 0))
      LKJCorrCholeskyPrior("L_Omega", dim: "J", eta: 2)
      VaryingVectorPrior("ab", indexedBy: "cafe", length: "J",
                         .multivariateNormalCholesky(
                           mean: "[a_bar, b_bar]'",
                           chol: "diag_pre_multiply(sigma_ab, L_Omega)"))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      int<lower=1> N_cafe;
      array[N] int<lower=1, upper=N_cafe> cafe;
      int J;
    }
    parameters {
      real a_bar;
      real b_bar;
      vector<lower=0>[J] sigma_ab;
      cholesky_factor_corr[J] L_Omega;
      array[N_cafe] vector[J] ab;
    }
    model {
      a_bar ~ normal(0, 5);
      b_bar ~ normal(0, 5);
      sigma_ab ~ exponential(1) T[0, ];
      L_Omega ~ lkj_corr_cholesky(2);
      ab ~ multi_normal_cholesky([a_bar, b_bar]', diag_pre_multiply(sigma_ab, L_Omega));
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Multivariate hierarchical priors Slice D: chained-indexed RHS

  /// Probe-and-lock golden for the chained-indexed (`ab[cafe][1]`) RHS
  /// shape. Builds the full cafe-style mean expression and asserts the
  /// loop emitter rewrites it as `ab[cafe[i]][1] + ab[cafe[i]][2]*afternoon[i]`
  /// inside a `for (i in 1:N) { ... }` body.
  @Test func varyingVectorChainedIndexMatchesGolden() throws {
    let data: UlamData = [
      "J":         .scalarInt(2),
      "cafe":      .integer([1, 2, 1, 2, 1, 2]),
      "afternoon": .integer([0, 0, 1, 1, 0, 1]),
      "wait":      .real([3.5, 2.7, 2.9, 2.1, 3.6, 2.0]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("wait", .normal("mu", "sigma"))
      Deterministic("mu", "ab[cafe][1] + ab[cafe][2] * afternoon")
      Prior("a_bar", .normal(0, 5))
      Prior("b_bar", .normal(0, 5))
      Prior("sigma", .exponential(1), truncation: Truncation(lower: 0))
      VectorPrior("sigma_ab", length: "J", .exponential(1),
                  truncation: Truncation(lower: 0))
      LKJCorrCholeskyPrior("L_Omega", dim: "J", eta: 2)
      VaryingVectorPrior("ab", indexedBy: "cafe", length: "J",
                         .multivariateNormalCholesky(
                           mean: "[a_bar, b_bar]'",
                           chol: "diag_pre_multiply(sigma_ab, L_Omega)"))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      int<lower=1> N_cafe;
      vector[N] afternoon;
      array[N] int<lower=1, upper=N_cafe> cafe;
      vector[N] wait;
      int J;
    }
    parameters {
      real a_bar;
      real b_bar;
      real<lower=0> sigma;
      vector<lower=0>[J] sigma_ab;
      cholesky_factor_corr[J] L_Omega;
      array[N_cafe] vector[J] ab;
    }
    model {
      vector[N] mu;
      for (i in 1:N) {
        mu[i] = ab[cafe[i]][1] + ab[cafe[i]][2]*afternoon[i];
      }
      a_bar ~ normal(0, 5);
      b_bar ~ normal(0, 5);
      sigma ~ exponential(1) T[0, ];
      sigma_ab ~ exponential(1) T[0, ];
      L_Omega ~ lkj_corr_cholesky(2);
      ab ~ multi_normal_cholesky([a_bar, b_bar]', diag_pre_multiply(sigma_ab, L_Omega));
      wait ~ normal(mu, sigma);
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - SUR Slices C + D + E: WaffleDivorce two-outcome model

  /// Full SUR shape end-to-end through the pure generator. Models
  /// Divorce and Marriage rates per US state as a 2-vector outcome
  /// predicted by a shared (intercept, MedianAgeMarriage) covariate
  /// matrix, with a `cov_matrix[J] Sigma` capturing cross-outcome
  /// error correlation.
  ///
  /// Exercises:
  /// - `.realMatrix` data shape for both `x` (N×K predictor matrix)
  ///   and `y` (N×J outcome matrix) — Slice C.
  /// - SUR pair detection in `BlockEmitter.modelBlock`: a
  ///   `Deterministic("mu", "x[n]*beta")` paired with a
  ///   `Likelihood("y", .multivariateNormal("mu", "Sigma"))` collapses
  ///   into a single `for (n in 1:N) { row_vector[J] mu = …;
  ///   y[n] ~ multi_normal(mu, Sigma); }` block — Slices D + E.
  /// - The matrix and cov_matrix parameter primitives from Slices
  ///   A + B carry over.
  ///
  /// Tiny 3-row synthetic dataset so the golden stays compact; the
  /// real `WaffleDivorce.csv` is exercised by Slice F's end-to-end
  /// artifact test.
  @Test func surWaffleDivorceShapeMatchesGolden() throws {
    let data: UlamData = [
      "K": .scalarInt(2),
      "J": .scalarInt(2),
      "x": .realMatrix(rows: 3, cols: 2,
                       values: [[1, 25.3], [1, 26.0], [1, 25.8]]),
      "y": .realMatrix(rows: 3, cols: 2,
                       values: [[12.7, 20.2], [11.0, 18.6], [13.5, 21.0]]),
    ]
    let model = UlamModel(data: data) {
      MatrixPrior("beta", rows: "K", cols: "J", .normal(0, 1))
      CovMatrixPrior("Sigma", dim: "J")
      Deterministic("mu", "x[n]*beta")
      Likelihood("y", .multivariateNormal(mu: "mu", sigma: "Sigma"))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      matrix[N, 2] x;
      matrix[N, 2] y;
      int J;
      int K;
    }
    parameters {
      matrix[K, J] beta;
      cov_matrix[J] Sigma;
    }
    model {
      to_vector(beta) ~ normal(0, 1);
      for (n in 1:N) {
        row_vector[J] mu = x[n]*beta;
        y[n] ~ multi_normal(mu, Sigma);
      }
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Phase 5.5 Slice G: two-grouping (reedfrog) demo

  /// Statistical Rethinking chapter 13 reedfrog-style model:
  /// survival ~ binomial(density, p) with both a per-tank random
  /// intercept and a per-size random offset. Verifies that Phase 5's
  /// `vectorParameters` / `indexColumns` accumulators handle two
  /// independent index columns cleanly. The RHS `a[tank] + s[size]`
  /// is `vector + vector` so it vectorises without needing Slice D.
  @Test func reedfrogTwoGroupingMatchesGolden() throws {
    let data: UlamData = [
      "y":       .integer([3, 5, 4, 2, 7, 8, 6, 7, 4, 5, 3, 6, 8, 9, 7, 8]),
      "density": .integer([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]),
      "tank":    .integer([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]),
      "size":    .integer([1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .binomial(n: "density", p: "p"))
      Link(.logit, lhs: "p", rhs: "a[tank] + s[size]")
      VaryingPrior("a", indexedBy: "tank", .normal("a_bar", "sigma_a"))
      VaryingPrior("s", indexedBy: "size", .normal(0, "sigma_s"))
      Prior("a_bar", .normal(0, 1.5))
      Prior("sigma_a", .normal(0, 1), truncation: Truncation(lower: 0))
      Prior("sigma_s", .normal(0, 1), truncation: Truncation(lower: 0))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      int<lower=1> N_size;
      int<lower=1> N_tank;
      array[N] int density;
      array[N] int<lower=1, upper=N_size> size;
      array[N] int<lower=1, upper=N_tank> tank;
      array[N] int<lower=0> y;
    }
    transformed data {
      for (i in 1:N) {
        if (y[i] > density[i]) {
          reject("y[", i, "] = ", y[i],
                 " > density[", i, "] = ", density[i],
                 " — binomial outcome must satisfy y[i] <= trials[i]");
        }
      }
    }
    parameters {
      vector[N_tank] a;
      vector[N_size] s;
      real a_bar;
      real<lower=0> sigma_a;
      real<lower=0> sigma_s;
    }
    model {
      vector[N] p;
      p = inv_logit(a[tank] + s[size]);
      a ~ normal(a_bar, sigma_a);
      s ~ normal(0, sigma_s);
      a_bar ~ normal(0, 1.5);
      sigma_a ~ normal(0, 1) T[0, ];
      sigma_s ~ normal(0, 1) T[0, ];
      y ~ binomial(density, p);
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Loop-body precedence regression

  /// Regression for the loop-body printer: a parenthesised sum
  /// multiplied by a vector must keep its parens in the emitted Stan
  /// source. Without the fix this round-tripped as `bp + bpc*x[i]`,
  /// which Stan reparses as `bp + (bpc*x[i])` — silently changing the
  /// arithmetic. Minimal repro of McElreath's m12.5 link RHS.
  @Test func loopBodyPreservesParenthesisedSum() throws {
    let data: UlamData = [
      "y":     .integer([0, 1, 0, 1]),
      "group": .integer([1, 2, 1, 2]),
      "x":     .real([0.1, 0.2, 0.3, 0.4]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "(a + b[group])*x")
      Prior("a", .normal(0, 1))
      VaryingPrior("b", indexedBy: "group", .normal(0, "sigma_b"))
      Prior("sigma_b", .exponential(1))
    }
    let stan = try stancode(model)
    #expect(stan.contains("p[i] = inv_logit((a + b[group[i]])*x[i]);"))
    #expect(!stan.contains("a + b[group[i]]*x[i]"))
  }

  // MARK: - Chimpanzees m12.5 (Statistical Rethinking ch. 13)

  /// McElreath's m12.5 — Bernoulli + logit with two independent
  /// `VaryingPrior`s (actor, block_id), a population intercept `a`,
  /// and a parenthesised slope `(bp + bpc*condition)*prosoc_left`.
  /// Exercises Slice F auto-promotion of two 0/1 integer columns to
  /// `vector[N]` and the loop-body precedence fix (the parens around
  /// `(bp + bpc*condition)` must survive into the emitted Stan).
  @Test func chimpanzeesM125MatchesGolden() throws {
    let data: UlamData = [
      "pulled_left": .integer([0, 1, 0, 1, 1, 0]),
      "actor":       .integer([1, 1, 2, 2, 3, 3]),
      "block_id":    .integer([1, 2, 1, 2, 1, 2]),
      "condition":   .integer([0, 0, 1, 1, 0, 1]),
      "prosoc_left": .integer([0, 1, 0, 1, 1, 0]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("pulled_left", .bernoulli(p: "p"))
      Link(.logit, lhs: "p",
           rhs: "a + a_actor[actor] + a_block[block_id] + (bp + bpc*condition)*prosoc_left")
      VaryingPrior("a_actor", indexedBy: "actor",    .normal(0, "sigma_actor"))
      VaryingPrior("a_block", indexedBy: "block_id", .normal(0, "sigma_block"))
      Prior("a",   .normal(0, 10))
      Prior("bp",  .normal(0, 10))
      Prior("bpc", .normal(0, 10))
      Prior("sigma_actor", .cauchy(0, 1), truncation: Truncation(lower: 0))
      Prior("sigma_block", .cauchy(0, 1), truncation: Truncation(lower: 0))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      int<lower=1> N_actor;
      int<lower=1> N_block_id;
      array[N] int<lower=1, upper=N_actor> actor;
      array[N] int<lower=1, upper=N_block_id> block_id;
      vector[N] condition;
      vector[N] prosoc_left;
      array[N] int<lower=0, upper=1> pulled_left;
    }
    parameters {
      vector[N_actor] a_actor;
      vector[N_block_id] a_block;
      real a;
      real bp;
      real bpc;
      real<lower=0> sigma_actor;
      real<lower=0> sigma_block;
    }
    model {
      vector[N] p;
      for (i in 1:N) {
        p[i] = inv_logit(a + a_actor[actor[i]] + a_block[block_id[i]] + (bp + bpc*condition[i])*prosoc_left[i]);
      }
      a_actor ~ normal(0, sigma_actor);
      a_block ~ normal(0, sigma_block);
      a ~ normal(0, 10);
      bp ~ normal(0, 10);
      bpc ~ normal(0, 10);
      sigma_actor ~ cauchy(0, 1) T[0, ];
      sigma_block ~ cauchy(0, 1) T[0, ];
      pulled_left ~ bernoulli(p);
    }
    """

    #expect(try stancode(model) == expected)
  }

  // MARK: - Phase 5.5 Slice F + D: varying slopes via loop emission

  /// Phase 5 already supports varying *intercepts* via `VaryingPrior`;
  /// varying *slopes* fall out of the same machinery — a vector
  /// parameter indexed by an integer data column, used multiplicatively
  /// against a real-typed predictor. Slice D's classifier detects the
  /// `vector * vector` (`b[group] * x`) shape and routes the link RHS
  /// through the new loop-body translator, which subscripts each
  /// per-row identifier (`x` → `x[i]`, `group` → `group[i]`) so Stan
  /// accepts the multiplication.
  @Test func varyingSlopesBernoulliMatchesGolden() throws {
    let data: UlamData = [
      "y":     .integer([0, 1, 0, 1, 1, 0, 1, 1]),
      "x":     .real([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]),
      "group": .integer([1, 2, 1, 2, 1, 2, 1, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a + b[group]*x")
      Prior("a", .normal(0, 1.5))
      VaryingPrior("b", indexedBy: "group", .normal("b_bar", "sigma_b"))
      Prior("b_bar", .normal(0, 1))
      Prior("sigma_b", .exponential(1))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      int<lower=1> N_group;
      array[N] int<lower=1, upper=N_group> group;
      vector[N] x;
      array[N] int<lower=0, upper=1> y;
    }
    parameters {
      real a;
      vector[N_group] b;
      real b_bar;
      real sigma_b;
    }
    model {
      vector[N] p;
      for (i in 1:N) {
        p[i] = inv_logit(a + b[group[i]]*x[i]);
      }
      a ~ normal(0, 1.5);
      b ~ normal(b_bar, sigma_b);
      b_bar ~ normal(0, 1);
      sigma_b ~ exponential(1);
      y ~ bernoulli(p);
    }
    """

    #expect(try stancode(model) == expected)
  }

  /// The non-centred decomposition is sample-statement-shaped — it
  /// has no `target += ..._lpdf` analogue, so combining it with
  /// `useLpdf: true` is also rejected. Closes Slice E's third
  /// validation case (the other two are normal-only-distribution and
  /// no-truncation).
  @Test func nonCenteredWithLpdfIsRejected() throws {
    let data: UlamData = [
      "y":     .integer([0, 1, 0, 1]),
      "group": .integer([1, 2, 1, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a[group]")
      VaryingPrior("a", indexedBy: "group",
                   .normal("a_bar", "sigma_a"),
                   useLpdf: true,
                   nonCentered: true)
      Prior("a_bar", .normal(0, 1.5))
      Prior("sigma_a", .exponential(1))
    }
    #expect(throws: DataInferenceError.self) {
      _ = try stancode(model)
    }
  }

  /// Truncation doesn't compose cleanly with the standard-normal raw
  /// form (`a_raw ~ std_normal() T[...]` is meaningful but the
  /// transformed-parameter shift breaks the bound on `a`). v1.5 just
  /// rejects it.
  @Test func nonCenteredWithTruncationIsRejected() throws {
    let data: UlamData = [
      "y":     .integer([0, 1, 0, 1]),
      "group": .integer([1, 2, 1, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a[group]")
      VaryingPrior("a", indexedBy: "group",
                   .normal("a_bar", "sigma_a"),
                   truncation: Truncation(lower: 0),
                   nonCentered: true)
      Prior("a_bar", .normal(0, 1.5))
      Prior("sigma_a", .exponential(1))
    }
    #expect(throws: DataInferenceError.self) {
      _ = try stancode(model)
    }
  }

  // MARK: - start: / constraints: overrides (2026-06-03)

  /// `constraints:` declares the `<lower=…>` bound on the parameter
  /// WITHOUT emitting the redundant `T[…]` sampling suffix. McElreath
  /// idiom for half-positive scale priors like `sigma ~ exponential(1)`
  /// where the prior's support already enforces lower=0.
  @Test func constraintsDeclareLowerWithoutTruncationSuffix() throws {
    let data: UlamData = [
      "y": .real([1.0, 2.0, 3.0, 2.5, 1.5]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .normal("mu", "sigma"))
      Prior("mu", .normal(0, 10))
      Prior("sigma", .exponential(1),
            constraints: Constraints(lower: 0))
    }
    let stan = try stancode(model)
    #expect(stan.contains("real<lower=0> sigma;"),
            "expected declaration-side <lower=0> on sigma; got:\n\(stan)")
    #expect(stan.contains("sigma ~ exponential(1);"),
            "expected plain ~ exponential(1) without T[0, ]; got:\n\(stan)")
    #expect(!stan.contains("sigma ~ exponential(1) T["),
            "expected NO T[…] suffix on sigma; got:\n\(stan)")
  }

  /// `constraints:` on `VaryingPrior` flows through the same dict and
  /// surfaces on the `vector<lower=…>[N_<col>]` declaration form.
  @Test func varyingPriorConstraintsDeclareLowerOnVectorType() throws {
    let data: UlamData = [
      "y":    .integer([3, 5, 4, 6]),
      "tank": .integer([1, 2, 1, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .poisson("lambda"))
      Link(.log, lhs: "lambda", rhs: "a[tank]")
      VaryingPrior("a", indexedBy: "tank",
                   .normal(0, 1),
                   constraints: Constraints(lower: 0))
    }
    let stan = try stancode(model)
    #expect(stan.contains("vector<lower=0>[N_tank] a;"),
            "expected vector<lower=0>[N_tank] a; got:\n\(stan)")
    #expect(!stan.contains("T[0,"),
            "expected NO T[0, …] suffix on VaryingPrior sampling line")
  }

  /// `start:` per-prior flows into `<name>.init.json` via the same
  /// `InferredModel.initValues` dict that `Inits([:])` populates.
  @Test func startKwargFlowsIntoInitJSON() throws {
    let data: UlamData = [
      "y": .real([170.0, 165.0, 180.0, 175.0]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .normal("mu", "sigma"))
      Prior("mu", .normal(178, 20), start: 178.0)
      Prior("sigma", .uniform(lower: 0, upper: 50),
            constraints: Constraints(lower: 0),
            start: 10.0)
    }
    let json = try stanInits(model)
    #expect(json.contains("\"mu\":178.0"),
            "expected mu=178.0 in init JSON; got: \(json)")
    #expect(json.contains("\"sigma\":10.0"),
            "expected sigma=10.0 in init JSON; got: \(json)")
  }

  /// Co-setting `constraints:` and `truncation:` on the same `Prior`
  /// is rejected via the new `constraintsConflictWithTruncation` error.
  @Test func constraintsAndTruncationOnSamePriorRejected() throws {
    let data: UlamData = ["y": .real([1.0, 2.0, 3.0])]
    let model = UlamModel(data: data) {
      Likelihood("y", .normal("mu", "sigma"))
      Prior("mu", .normal(0, 1))
      Prior("sigma", .exponential(1),
            truncation: Truncation(lower: 0),
            constraints: Constraints(lower: 0))
    }
    #expect(throws: DataInferenceError.self) {
      _ = try stancode(model)
    }
  }

  /// Two `Prior`s on the same name with disagreeing `constraints:`
  /// reuses the existing `conflictingParameterConstraints` error path.
  @Test func conflictingConstraintsOnSameNameRejected() throws {
    let data: UlamData = ["y": .real([1.0, 2.0])]
    let model = UlamModel(data: data) {
      Likelihood("y", .normal("mu", "sigma"))
      Prior("mu", .normal(0, 1), constraints: Constraints(lower: 0))
      Prior("mu", .normal(0, 1), constraints: Constraints(lower: -10))
      Prior("sigma", .exponential(1))
    }
    #expect(throws: DataInferenceError.self) {
      _ = try stancode(model)
    }
  }

  /// When per-prior `start:` and a later `Inits([:])` set the same key,
  /// `Inits([:])` overlays (last-write-wins in walk order).
  @Test func initsOverridesPerPriorStart() throws {
    let data: UlamData = ["y": .real([170.0, 165.0])]
    let model = UlamModel(data: data) {
      Likelihood("y", .normal("mu", "sigma"))
      Prior("mu", .normal(178, 20), start: 100.0)
      Prior("sigma", .exponential(1),
            constraints: Constraints(lower: 0))
      Inits(["mu": 178.0])
    }
    let json = try stanInits(model)
    #expect(json.contains("\"mu\":178.0"),
            "Inits([:]) should overlay per-prior start; got: \(json)")
  }

  // MARK: - Nested groupings (2026-06-03)

  /// McElreath-style `a[country, region]` model: one parameter indexed
  /// by two integer data columns simultaneously, distinct from two
  /// summed `VaryingPrior` effects. Declares `matrix[N_country, N_region]
  /// a;` and emits the iid `to_vector(a) ~ normal(a_bar, sigma_a);`
  /// flat prior over every cell. The mu RHS uses the new comma-form
  /// matrix subscript, which forces loop emission with both index
  /// columns subscripted by the loop variable.
  @Test func nestedGroupingsMatchesGolden() throws {
    let data: UlamData = [
      "y":       .real([1.0, 2.0, 3.0, 2.5, 1.5, 2.8, 1.2, 2.6]),
      "x":       .real([0.1, 0.3, 0.5, 0.7, 0.4, 0.6, 0.2, 0.8]),
      "country": .integer([1, 1, 2, 2, 3, 3, 1, 2]),
      "region":  .integer([1, 2, 1, 2, 1, 2, 1, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .normal("mu", "sigma"))
      Deterministic("mu", "a[country, region] + bX*x")
      NestedVaryingPrior("a", indexedBy: ["country", "region"],
                         .normal("a_bar", "sigma_a"))
      Prior("a_bar", .normal(0, 1))
      Prior("sigma_a", .exponential(1),
            constraints: Constraints(lower: 0))
      Prior("bX", .normal(0, 1))
      Prior("sigma", .exponential(1),
            constraints: Constraints(lower: 0))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      int<lower=1> N_country;
      int<lower=1> N_region;
      array[N] int<lower=1, upper=N_country> country;
      array[N] int<lower=1, upper=N_region> region;
      vector[N] x;
      vector[N] y;
    }
    parameters {
      matrix[N_country, N_region] a;
      real a_bar;
      real<lower=0> sigma_a;
      real bX;
      real<lower=0> sigma;
    }
    model {
      vector[N] mu;
      for (i in 1:N) {
        mu[i] = a[country[i], region[i]] + bX*x[i];
      }
      to_vector(a) ~ normal(a_bar, sigma_a);
      a_bar ~ normal(0, 1);
      sigma_a ~ exponential(1);
      bX ~ normal(0, 1);
      sigma ~ exponential(1);
      y ~ normal(mu, sigma);
    }
    """

    #expect(try stancode(model) == expected)
  }

  /// v1 rejects 3+ grouping dimensions with a clear error.
  @Test func nestedVaryingPriorRejectsThreeDimensions() throws {
    let data: UlamData = [
      "y":       .real([1.0, 2.0]),
      "country": .integer([1, 2]),
      "region":  .integer([1, 2]),
      "year":    .integer([1, 2]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .normal("mu", "sigma"))
      Deterministic("mu", "a[country, region]")
      NestedVaryingPrior("a",
                         indexedBy: ["country", "region", "year"],
                         .normal("a_bar", "sigma_a"))
      Prior("a_bar", .normal(0, 1))
      Prior("sigma_a", .exponential(1),
            constraints: Constraints(lower: 0))
      Prior("sigma", .exponential(1),
            constraints: Constraints(lower: 0))
    }
    #expect(throws: DataInferenceError.self) {
      _ = try stancode(model)
    }
  }

  // MARK: - Crossed random effects with correlations (2026-06-03)

  /// brms-style `y ~ x + (1+x|subject) + (1+x|item)` shape with two
  /// **crossed** correlated varying effects — distinct group columns
  /// (`subject`, `item`), each carrying its own Cholesky factor, σ
  /// vector, and per-group J cardinality (`J_subject`, `J_item`). The
  /// existing `VaryingVectorPrior` + `LKJCorrCholeskyPrior` +
  /// `VectorPrior` building blocks compose without source changes —
  /// this test locks the multi-grouping wiring in place.
  @Test func varyingVectorCrossedEffectsMatchesGolden() throws {
    let data: UlamData = [
      "J_subject": .scalarInt(2),
      "J_item":    .scalarInt(2),
      "subject":   .integer([1, 1, 2, 2, 1, 2]),
      "item":      .integer([1, 2, 1, 2, 1, 2]),
      "x":         .real([0.1, 0.2, 0.3, 0.4, 0.5, 0.6]),
      "y":         .real([1.0, 1.5, 2.0, 1.8, 1.2, 1.9]),
    ]
    let model = UlamModel(data: data) {
      Likelihood("y", .normal("mu", "sigma"))
      Deterministic("mu",
        "ab_subject[subject][1] + ab_subject[subject][2]*x + ab_item[item][1] + ab_item[item][2]*x")
      Prior("a_bar", .normal(0, 5))
      Prior("b_bar", .normal(0, 5))
      Prior("sigma", .exponential(1), truncation: Truncation(lower: 0))
      // subject grouping
      VectorPrior("sigma_subject", length: "J_subject", .exponential(1),
                  truncation: Truncation(lower: 0))
      LKJCorrCholeskyPrior("L_subject", dim: "J_subject", eta: 2)
      VaryingVectorPrior("ab_subject", indexedBy: "subject", length: "J_subject",
                         .multivariateNormalCholesky(
                           mean: "[a_bar, b_bar]'",
                           chol: "diag_pre_multiply(sigma_subject, L_subject)"))
      // item grouping (crossed)
      VectorPrior("sigma_item", length: "J_item", .exponential(1),
                  truncation: Truncation(lower: 0))
      LKJCorrCholeskyPrior("L_item", dim: "J_item", eta: 2)
      VaryingVectorPrior("ab_item", indexedBy: "item", length: "J_item",
                         .multivariateNormalCholesky(
                           mean: "[a_bar, b_bar]'",
                           chol: "diag_pre_multiply(sigma_item, L_item)"))
    }

    let expected = """
    // Generated by SwiftStan ulam port.
    data {
      int<lower=1> N;
      int<lower=1> N_item;
      int<lower=1> N_subject;
      array[N] int<lower=1, upper=N_item> item;
      array[N] int<lower=1, upper=N_subject> subject;
      vector[N] x;
      vector[N] y;
      int J_item;
      int J_subject;
    }
    parameters {
      real a_bar;
      real b_bar;
      real<lower=0> sigma;
      vector<lower=0>[J_subject] sigma_subject;
      cholesky_factor_corr[J_subject] L_subject;
      array[N_subject] vector[J_subject] ab_subject;
      vector<lower=0>[J_item] sigma_item;
      cholesky_factor_corr[J_item] L_item;
      array[N_item] vector[J_item] ab_item;
    }
    model {
      vector[N] mu;
      for (i in 1:N) {
        mu[i] = ab_subject[subject[i]][1] + ab_subject[subject[i]][2]*x[i] + ab_item[item[i]][1] + ab_item[item[i]][2]*x[i];
      }
      a_bar ~ normal(0, 5);
      b_bar ~ normal(0, 5);
      sigma ~ exponential(1) T[0, ];
      sigma_subject ~ exponential(1) T[0, ];
      L_subject ~ lkj_corr_cholesky(2);
      ab_subject ~ multi_normal_cholesky([a_bar, b_bar]', diag_pre_multiply(sigma_subject, L_subject));
      sigma_item ~ exponential(1) T[0, ];
      L_item ~ lkj_corr_cholesky(2);
      ab_item ~ multi_normal_cholesky([a_bar, b_bar]', diag_pre_multiply(sigma_item, L_item));
      y ~ normal(mu, sigma);
    }
    """

    #expect(try stancode(model) == expected)
  }
}

// MARK: - End-to-end artifact emission

/// Drives `ulam()` for each built-in demo so the .stan source,
/// .data.json, compiled binary, and cmdstan sample outputs land
/// under `~/Documents/StanCases/<name>/`. These cover the same
/// five models exposed by the `stan ulam --model …` CLI subcommand.
///
/// cmdstan is resolved from `$CMDSTAN` with the same fallback the CLI
/// uses (`/Users/rob/Projects/StanSupport/cmdstan`).
@Suite("Ulam end-to-end artifact tests", .enabled(if: ProcessInfo.processInfo.environment["CMDSTAN"] != nil, "Set $CMDSTAN to run integration tests"))
struct UlamArtifactEmissionTests {
  init() { _ = TestCaseRootBootstrap.install }


  static let cmdstan: String = {
    if let env = ProcessInfo.processInfo.environment["CMDSTAN"], !env.isEmpty {
      return env
    }
    return ProcessInfo.processInfo.environment["CMDSTAN"] ?? ""
  }()

  /// Runs `ulam()` end-to-end and verifies the artifacts the pipeline
  /// produces under the V2.1 layout: `<root>/<name>/Results/<name>.stan`
  /// and `<name>.data.json`. In addition this helper writes the
  /// `<Name>.ulam.swift` smoke driver into `<root>/<name>/Preliminaries/`
  /// — the "ulam input" alongside the generated outputs.
  static func runUlamAndCheckArtifacts(name: String,
                                       filenameStem: String,
                                       ulamSource: String,
                                       model: UlamModel) throws {
    let result = ulam(model, name: name, cmdstan: cmdstan)
    try #require(result.1.isEmpty, "ulam returned an error: \(result.1)")

    let paths = casePaths(for: name)
    let fm = FileManager.default
    #expect(fm.fileExists(atPath: paths.results.appendingPathComponent("\(name).stan").path))
    #expect(fm.fileExists(atPath: paths.results.appendingPathComponent("\(name).data.json").path))

    let smokePath = paths.preliminaries.appendingPathComponent("\(filenameStem).ulam.swift")
    try ulamSource.write(to: smokePath,
                         atomically: true,
                         encoding: .utf8)
    #expect(fm.fileExists(atPath: smokePath.path))
  }

  @Test func bernoulliArtifactsEmitted() throws {
    try Self.runUlamAndCheckArtifacts(name: "bernoulli",
                                      filenameStem: "Bernoulli",
                                      ulamSource: bernoulliUlamSwift,
                                      model: SwiftStan.Ulam.bernoulliDemo())
  }

  @Test func poissonArtifactsEmitted() throws {
    try Self.runUlamAndCheckArtifacts(name: "poisson",
                                      filenameStem: "Poisson",
                                      ulamSource: poissonUlamSwift,
                                      model: SwiftStan.Ulam.poissonDemo())
  }

  @Test func binomialArtifactsEmitted() throws {
    try Self.runUlamAndCheckArtifacts(name: "binomial",
                                      filenameStem: "Binomial",
                                      ulamSource: binomialUlamSwift,
                                      model: SwiftStan.Ulam.binomialDemo())
  }

  @Test func ucbArtifactsEmitted() throws {
    try Self.runUlamAndCheckArtifacts(name: "ucb",
                                      filenameStem: "UCB",
                                      ulamSource: ucbUlamSwift,
                                      model: SwiftStan.Ulam.ucbDemo())
  }

  @Test func dmvnormArtifactsEmitted() throws {
    try Self.runUlamAndCheckArtifacts(name: "dmvnorm",
                                      filenameStem: "Dmvnorm",
                                      ulamSource: dmvnormUlamSwift,
                                      model: SwiftStan.Ulam.dmvnormDemo())
  }

  /// Statistical Rethinking ch.13 reedfrog two-grouping model. Has
  /// 5 base parameters + per-tank and per-size random effects, but
  /// the structure is the same shape as the existing multilevel +
  /// UCB demos (no `vector*vector` in the link RHS), so cmdstan
  /// converges quickly.
  @Test func reedfrogArtifactsEmitted() throws {
    try Self.runUlamAndCheckArtifacts(name: "reedfrog",
                                      filenameStem: "Reedfrog",
                                      ulamSource: reedfrogUlamSwift,
                                      model: SwiftStan.Ulam.reedfrogDemo())
  }

  /// Multivariate hierarchical priors end-to-end test (2026-05-31):
  /// drives the cafe model (Slices A–D) through `ulam()` against a
  /// 60-row synthetic dataset. Asserts only artifact emission — the
  /// LKJ correlation is weakly identified on small N, so the existing
  /// pattern of checking `.stan` + `.data.json` rather than R-hat
  /// applies.
  @Test func cafeArtifactsEmitted() throws {
    try Self.runUlamAndCheckArtifacts(name: "cafe",
                                      filenameStem: "Cafe",
                                      ulamSource: cafeUlamSwift,
                                      model: SwiftStan.Ulam.cafeDemo())
  }

  /// McElreath's m12.5 driven by the real Rethinking chimpanzees dataset
  /// (504 rows). Reads `~/.julia/dev/Stan/data/chimpanzees.csv`, drops
  /// the `recipient` column (it carries `NA` values), renames `block` →
  /// `block_id` (Stan reserves `block`), builds the DSL model, and runs
  /// the full ulam pipeline. Skips with a clear message if the upstream
  /// CSV isn't present on the developer's machine.
  @Test func chimpanzeesArtifactsEmitted() throws {
    // Uses the bundled `Tests/TestDataFiles/chimpanzees.csv`
    // fixture (comma-delimited, `block` already renamed to `block_id`, no
    // `recipient` column) so the test runs from a clean checkout without
    // depending on a developer-local data directory.
    let csvURL = try #require(
      Bundle.module.url(forResource: "chimpanzees",
                        withExtension: "csv",
                        subdirectory: "TestDataFiles"),
      "bundled chimpanzees.csv fixture missing — check Package.swift resources:")
    let fm = FileManager.default

    let parsed = try Self.parseChimpanzeesCsv(at: csvURL.path)
    let paths = casePaths(for: "chimpanzees")
    let data: UlamData = [
      "pulled_left": .integer(parsed["pulled_left"]!),
      "actor":       .integer(parsed["actor"]!),
      "block_id":    .integer(parsed["block_id"]!),
      "condition":   .integer(parsed["condition"]!),
      "prosoc_left": .integer(parsed["prosoc_left"]!),
    ]

    let model = UlamModel(data: data) {
      Likelihood("pulled_left", .bernoulli(p: "p"))
      Link(.logit, lhs: "p",
           rhs: "a + a_actor[actor] + a_block[block_id] + (bp + bpc*condition)*prosoc_left")
      VaryingPrior("a_actor", indexedBy: "actor",    .normal(0, "sigma_actor"))
      VaryingPrior("a_block", indexedBy: "block_id", .normal(0, "sigma_block"))
      Prior("a",   .normal(0, 10))
      Prior("bp",  .normal(0, 10))
      Prior("bpc", .normal(0, 10))
      Prior("sigma_actor", .cauchy(0, 1), truncation: Truncation(lower: 0))
      Prior("sigma_block", .cauchy(0, 1), truncation: Truncation(lower: 0))
    }

    let result = ulam(model, name: "chimpanzees", cmdstan: Self.cmdstan)
    try #require(result.1.isEmpty, "ulam returned an error: \(result.1)")

    #expect(fm.fileExists(atPath: paths.results.appendingPathComponent("chimpanzees.stan").path))
    #expect(fm.fileExists(atPath: paths.results.appendingPathComponent("chimpanzees.data.json").path))
  }

  /// SUR Slice F: McElreath-adjacent end-to-end test. Reads
  /// `~/.julia/dev/Stan/data/WaffleDivorce.csv` (50 US states; same
  /// fixture directory as chimpanzees), models Divorce + Marriage as
  /// jointly multivariate-normal predicted by [1, MedianAgeMarriage],
  /// and drives the full `ulam()` pipeline. Asserts the standard
  /// artifact set lands in `~/Documents/StanCases/sur/Results/`.
  ///
  /// Predictors are standardised to zero mean / unit variance so the
  /// Sigma off-diagonal is well-identified at N=50; without
  /// standardisation cmdstan's R-hat can creep above 1.05 on the
  /// intercept row of `beta`.
  @Test func surArtifactsEmitted() throws {
    // Uses the bundled `Tests/TestDataFiles/WaffleDivorce.csv`
    // fixture (semicolon-delimited) so the test runs from a clean checkout
    // without depending on a developer-local data directory.
    let csvURL = try #require(
      Bundle.module.url(forResource: "WaffleDivorce",
                        withExtension: "csv",
                        subdirectory: "TestDataFiles"),
      "bundled WaffleDivorce.csv fixture missing — check Package.swift resources:")
    let fm = FileManager.default

    let raw = try String(contentsOf: csvURL, encoding: .utf8)
    let lines = raw.split(whereSeparator: \.isNewline).map(String.init)
    let headers = lines[0].split(separator: ";").map {
      String($0).trimmingCharacters(in: CharacterSet(charactersIn: "\""))
    }
    let idxMAM = headers.firstIndex(of: "MedianAgeMarriage")!
    let idxMar = headers.firstIndex(of: "Marriage")!
    let idxDiv = headers.firstIndex(of: "Divorce")!
    var medianAge: [Double] = []
    var marriage: [Double] = []
    var divorce: [Double] = []
    for row in lines.dropFirst() {
      let v = row.split(separator: ";", omittingEmptySubsequences: false).map {
        String($0).trimmingCharacters(in: CharacterSet(charactersIn: "\""))
      }
      medianAge.append(Double(v[idxMAM])!)
      marriage.append(Double(v[idxMar])!)
      divorce.append(Double(v[idxDiv])!)
    }
    let N = medianAge.count

    // Standardise the predictor column. Outcomes left on natural scale.
    let meanAge = medianAge.reduce(0, +) / Double(N)
    let varAge = medianAge.map { pow($0 - meanAge, 2) }.reduce(0, +) / Double(N - 1)
    let sdAge = sqrt(varAge)
    let mamStd = medianAge.map { ($0 - meanAge) / sdAge }

    let xRows: [[Double]] = (0..<N).map { [1.0, mamStd[$0]] }
    let yRows: [[Double]] = (0..<N).map { [divorce[$0], marriage[$0]] }

    let data: UlamData = [
      "K": .scalarInt(2),
      "J": .scalarInt(2),
      "x": .realMatrix(rows: N, cols: 2, values: xRows),
      "y": .realMatrix(rows: N, cols: 2, values: yRows),
    ]
    let model = UlamModel(data: data) {
      MatrixPrior("beta", rows: "K", cols: "J", .normal(0, 5))
      CovMatrixPrior("Sigma", dim: "J")
      Deterministic("mu", "x[n]*beta")
      Likelihood("y", .multivariateNormal(mu: "mu", sigma: "Sigma"))
    }

    let result = ulam(model, name: "sur", cmdstan: Self.cmdstan)
    try #require(result.1.isEmpty, "ulam returned an error: \(result.1)")

    let paths = casePaths(for: "sur")
    #expect(fm.fileExists(atPath: paths.results.appendingPathComponent("sur.stan").path))
    #expect(fm.fileExists(atPath: paths.results.appendingPathComponent("sur.data.json").path))
  }

  /// Minimal CSV parser tailored to McElreath's chimpanzees.csv:
  /// `;`-separated, quoted headers, drops the `recipient` column (which
  /// holds `NA`). Returns one Int column per kept header.
  private static func parseChimpanzeesCsv(at path: String) throws -> [String: [Int]] {
    let raw = try String(contentsOfFile: path, encoding: .utf8)
    let lines = raw.split(whereSeparator: \.isNewline).map(String.init)
    let quotes = CharacterSet(charactersIn: "\"")
    let headers = lines[0].split(separator: ",").map {
      $0.trimmingCharacters(in: quotes)
    }
    let keepIndices = headers.enumerated()
      .filter { $0.element != "recipient" }
      .map { $0.offset }
    var columns: [String: [Int]] = [:]
    for i in keepIndices { columns[headers[i]] = [] }
    for row in lines.dropFirst() {
      let values = row.split(separator: ",", omittingEmptySubsequences: false).map(String.init)
      for i in keepIndices {
        guard let v = Int(values[i].trimmingCharacters(in: quotes)) else {
          throw ChimpanzeesParseError.nonInteger(column: headers[i], value: values[i])
        }
        columns[headers[i]]!.append(v)
      }
    }
    return columns
  }

  enum ChimpanzeesParseError: Error {
    case nonInteger(column: String, value: String)
  }

  // VaryingSlopes deliberately has no e2e artifact-emission test:
  // Slice D's loop emission makes the generated `.stan` valid
  // cmdstan input (no more `vector*vector` rejection), but the
  // demo's small synthetic dataset converges slowly under the
  // helper's default `num_chains=4 num_samples=1000`. Run
  // `stan ulam --model VaryingSlopes -V` from the CLI to verify
  // end-to-end. The Stan source generation is covered by
  // `varyingSlopesBernoulliMatchesGolden`.
}

// MARK: - Ulam input ("smoke") source templates
//
// Self-contained Swift source files that document the DSL form of
// each demo model. Written alongside the generated .stan / .data.json
// / cmdstan outputs by the artifact-emission tests above. The build
// instructions in each header reproduce just the Stan-source half of
// the pipeline (no cmdstan invocation) for quick inspection.

private let bernoulliUlamSwift = """
// Bernoulli.ulam.swift
//
// Phase 1 ulam-port input: the canonical Statistical Rethinking opening
// example expressed via the Swift result-builder DSL.
//
// Regenerate the .stan + .data.json + cmdstan output artifacts with:
//
//   stan ulam --model Bernoulli [-V]
//
// Or run this file standalone to print just the Stan source:
//
//   cd ~/Projects/Swift/SwiftStan
//   swiftc -parse-as-library -o /tmp/ulam_bernoulli \\
//     Sources/SwiftStan/Ulam/AST/*.swift \\
//     Sources/SwiftStan/Ulam/Builder/*.swift \\
//     Sources/SwiftStan/Ulam/Data/*.swift \\
//     Sources/SwiftStan/Ulam/Generator/*.swift \\
//     ~/Documents/StanCases/bernoulli/Preliminaries/Bernoulli.ulam.swift
//   /tmp/ulam_bernoulli

@main
struct BernoulliSmoke {
  static func main() {
    let data: UlamData = [
      "y": .integer([0, 1, 0, 1, 1, 0, 1, 1, 1, 0]),
      "x": .real([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]),
    ]

    let model = UlamModel(data: data) {
      Likelihood("y", .bernoulli(p: "p"))
      Link(.logit, lhs: "p", rhs: "a + b*x")
      Prior("a", .normal(0, 1.5))
      Prior("b", .normal(0, 0.5))
    }

    do {
      print(try stancode(model))
    } catch {
      print("ERROR: \\(error)")
    }
  }
}
"""

private let poissonUlamSwift = """
// Poisson.ulam.swift
//
// Phase 3 ulam-port input: Poisson regression with a log link, the
// `target += poisson_lpmf(y | lambda)` emission path (useLpdf: true),
// and a Cauchy prior on the slope.
//
// Regenerate the .stan + .data.json + cmdstan output artifacts with:
//
//   stan ulam --model Poisson [-V]
//
// Or run this file standalone to print just the Stan source:
//
//   cd ~/Projects/Swift/SwiftStan
//   swiftc -parse-as-library -o /tmp/ulam_poisson \\
//     Sources/SwiftStan/Ulam/AST/*.swift \\
//     Sources/SwiftStan/Ulam/Builder/*.swift \\
//     Sources/SwiftStan/Ulam/Data/*.swift \\
//     Sources/SwiftStan/Ulam/Generator/*.swift \\
//     ~/Documents/StanCases/poisson/Preliminaries/Poisson.ulam.swift
//   /tmp/ulam_poisson

@main
struct PoissonSmoke {
  static func main() {
    let data: UlamData = [
      "y": .integer([2, 1, 3, 5, 4, 6, 8, 7]),
      "x": .real([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]),
    ]

    let model = UlamModel(data: data) {
      Likelihood("y", .poisson("lambda"), useLpdf: true)
      Link(.log, lhs: "lambda", rhs: "a + b*x")
      Prior("a", .normal(0, 1.5))
      Prior("b", .cauchy(0, 1))
    }

    do {
      print(try stancode(model))
    } catch {
      print("ERROR: \\(error)")
    }
  }
}
"""

private let binomialUlamSwift = """
// Binomial.ulam.swift
//
// Phase 3 ulam-port input: binomial logistic regression — outcomes are
// `successes` out of `trials`, predictor `x`, logit link, and a
// truncated half-normal prior on the slope coefficient.
//
// Regenerate the .stan + .data.json + cmdstan output artifacts with:
//
//   stan ulam --model Binomial [-V]
//
// Or run this file standalone to print just the Stan source:
//
//   cd ~/Projects/Swift/SwiftStan
//   swiftc -parse-as-library -o /tmp/ulam_binomial \\
//     Sources/SwiftStan/Ulam/AST/*.swift \\
//     Sources/SwiftStan/Ulam/Builder/*.swift \\
//     Sources/SwiftStan/Ulam/Data/*.swift \\
//     Sources/SwiftStan/Ulam/Generator/*.swift \\
//     ~/Documents/StanCases/binomial/Preliminaries/Binomial.ulam.swift
//   /tmp/ulam_binomial

@main
struct BinomialSmoke {
  static func main() {
    let data: UlamData = [
      "successes": .integer([2, 3, 1, 4, 5, 6, 7, 8]),
      "trials":    .integer([5, 5, 5, 5, 10, 10, 10, 10]),
      "x":         .real([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]),
    ]

    let model = UlamModel(data: data) {
      Likelihood("successes", .binomial(n: "trials", p: "theta"))
      Link(.logit, lhs: "theta", rhs: "a + b*x")
      Prior("a", .normal(0, 1.5))
      Prior("b", .normal(0, 1), truncation: Truncation(lower: 0))
    }

    do {
      print(try stancode(model))
    } catch {
      print("ERROR: \\(error)")
    }
  }
}
"""

private let ucbUlamSwift = """
// UCB.ulam.swift
//
// Phase 5 ulam-port input: McElreath's UCB Berkeley admissions varying-
// intercept binomial logistic regression. Demonstrates `VaryingPrior`
// over a `dept` index column plus a half-normal prior on the group-
// level scale.
//
// Regenerate the .stan + .data.json + cmdstan output artifacts with:
//
//   stan ulam --model UCB [-V]
//
// Or run this file standalone to print just the Stan source:
//
//   cd ~/Projects/Swift/SwiftStan
//   swiftc -parse-as-library -o /tmp/ulam_ucb \\
//     Sources/SwiftStan/Ulam/AST/*.swift \\
//     Sources/SwiftStan/Ulam/Builder/*.swift \\
//     Sources/SwiftStan/Ulam/Data/*.swift \\
//     Sources/SwiftStan/Ulam/Generator/*.swift \\
//     ~/Documents/StanCases/ucb/Preliminaries/UCB.ulam.swift
//   /tmp/ulam_ucb

@main
struct UCBSmoke {
  static func main() {
    let data: UlamData = [
      "admit":        .integer([512, 89, 353, 17, 120, 202, 138, 131, 53, 94, 22, 24]),
      "applications": .integer([825, 108, 560, 25, 325, 593, 417, 375, 191, 393, 373, 341]),
      // `male` is a 0/1 integer predictor. Phase 5.5 Slice C
      // auto-promotes integer columns that appear in real-typed
      // arithmetic (here: `b*male`) to `vector[N]`, so the integer
      // declaration here is exactly what we want.
      "male":         .integer([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]),
      "dept":         .integer([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6]),
    ]

    let model = UlamModel(data: data) {
      Likelihood("admit", .binomial(n: "applications", p: "p"))
      Link(.logit, lhs: "p", rhs: "a[dept] + b*male")
      VaryingPrior("a", indexedBy: "dept",
                   .normal("abar", "sigma"))
      Prior("abar", .normal(0, 4))
      Prior("sigma", .normal(0, 1), truncation: Truncation(lower: 0))
      Prior("b", .normal(0, 1))
    }

    do {
      print(try stancode(model))
    } catch {
      print("ERROR: \\(error)")
    }
  }
}
"""

private let dmvnormUlamSwift = """
// Dmvnorm.ulam.swift
//
// Phase 6 ulam-port input: minimum-viable multivariate-normal —
// bivariate-mean estimation with a fixed prior covariance and a fixed
// observation covariance. `mu ~ multi_normal(zero, Sigma_prior)` and
// `y ~ multi_normal(mu, Sigma_obs)`. The cardinality symbol `K` is
// bound to 2 via the inner length of the matrix-shaped data columns.
//
// Regenerate the .stan + .data.json + cmdstan output artifacts with:
//
//   stan ulam --model Dmvnorm [-V]
//
// Or run this file standalone to print just the Stan source:
//
//   cd ~/Projects/Swift/SwiftStan
//   swiftc -parse-as-library -o /tmp/ulam_dmvnorm \\
//     Sources/SwiftStan/Ulam/AST/*.swift \\
//     Sources/SwiftStan/Ulam/Builder/*.swift \\
//     Sources/SwiftStan/Ulam/Data/*.swift \\
//     Sources/SwiftStan/Ulam/Generator/*.swift \\
//     ~/Documents/StanCases/dmvnorm/Preliminaries/Dmvnorm.ulam.swift
//   /tmp/ulam_dmvnorm

@main
struct DmvnormSmoke {
  static func main() {
    let observations: [[Double]] = [
      [1.10, 0.42], [0.92, 0.61], [1.05, 0.48], [1.21, 0.34],
      [0.88, 0.55], [1.14, 0.39], [1.02, 0.52], [0.95, 0.58],
      [1.18, 0.36], [1.08, 0.47], [0.97, 0.56], [1.03, 0.50],
      [1.12, 0.41], [0.99, 0.54], [1.16, 0.37], [0.91, 0.60],
      [1.07, 0.46], [1.04, 0.49], [0.96, 0.57], [1.10, 0.43],
    ]
    let data: UlamData = [
      "y":           .realArrayVector(rowCount: observations.count,
                                      colCount: 2,
                                      values: observations),
      "zero":        .realVector(length: 2, values: [0, 0]),
      "Sigma_prior": .realCovMatrix(dim: 2, values: [[1, 0.5], [0.5, 1]]),
      "Sigma_obs":   .realCovMatrix(dim: 2,
                                    values: [[0.02, 0.005], [0.005, 0.02]]),
    ]

    let model = UlamModel(data: data) {
      Likelihood("y", .multivariateNormal(mu: "mu", sigma: "Sigma_obs"))
      VectorPrior("mu", length: "K",
                  .multivariateNormal(mu: "zero", sigma: "Sigma_prior"))
    }

    do {
      print(try stancode(model))
    } catch {
      print("ERROR: \\(error)")
    }
  }
}
"""

private let cafeUlamSwift = """
// Cafe.ulam.swift
//
// Multivariate hierarchical priors ulam-port input: McElreath
// chapter-14 cafes model. Per-cafe random intercept α and slope β are
// drawn from a bivariate normal with LKJ-Cholesky prior on the
// correlation factor and an exponential prior on the per-dimension
// scale. Exercises LKJCorrCholeskyPrior + multi_normal_cholesky +
// VaryingVectorPrior + chained-indexed RHS (`ab[cafe][k]`) end-to-end.
//
// Regenerate the .stan + .data.json + cmdstan output artifacts with:
//
//   stan ulam --model Cafe [-V]
//
// Or run this file standalone to print just the Stan source:
//
//   cd ~/Projects/Swift/SwiftStan
//   swiftc -parse-as-library -o /tmp/ulam_cafe \\
//     Sources/SwiftStan/Ulam/AST/*.swift \\
//     Sources/SwiftStan/Ulam/Builder/*.swift \\
//     Sources/SwiftStan/Ulam/Data/*.swift \\
//     Sources/SwiftStan/Ulam/Generator/*.swift \\
//     ~/Documents/StanCases/cafe/Preliminaries/Cafe.ulam.swift
//   /tmp/ulam_cafe

@main
struct CafeSmoke {
  static func main() {
    let cafe: [Int] = (1...6).flatMap { Array(repeating: $0, count: 10) }
    let afternoon: [Int] = Array(repeating: [0,0,0,0,0,1,1,1,1,1],
                                 count: 6).flatMap { $0 }
    let wait: [Double] = [
      3.81, 4.22, 3.95, 4.14, 4.08, 2.46, 2.74, 2.61, 2.39, 2.55,
      3.04, 3.34, 3.18, 3.27, 3.11, 2.31, 2.52, 2.40, 2.48, 2.36,
      3.58, 3.81, 3.62, 3.74, 3.69, 2.40, 2.62, 2.54, 2.45, 2.58,
      2.81, 2.94, 2.86, 3.01, 2.92, 2.32, 2.50, 2.41, 2.38, 2.45,
      4.04, 4.31, 4.12, 4.24, 4.18, 2.42, 2.65, 2.51, 2.58, 2.46,
      3.27, 3.50, 3.38, 3.46, 3.41, 2.44, 2.62, 2.55, 2.49, 2.58,
    ]
    let data: UlamData = [
      "J":         .scalarInt(2),
      "cafe":      .integer(cafe),
      "afternoon": .integer(afternoon),
      "wait":      .real(wait),
    ]

    let model = UlamModel(data: data) {
      Likelihood("wait", .normal("mu", "sigma"))
      Deterministic("mu", "ab[cafe][1] + ab[cafe][2] * afternoon")
      Prior("a_bar", .normal(0, 5))
      Prior("b_bar", .normal(0, 5))
      Prior("sigma", .exponential(1), truncation: Truncation(lower: 0))
      VectorPrior("sigma_ab", length: "J", .exponential(1),
                  truncation: Truncation(lower: 0))
      LKJCorrCholeskyPrior("L_Omega", dim: "J", eta: 2)
      VaryingVectorPrior("ab", indexedBy: "cafe", length: "J",
                         .multivariateNormalCholesky(
                           mean: "[a_bar, b_bar]'",
                           chol: "diag_pre_multiply(sigma_ab, L_Omega)"))
    }

    do {
      print(try stancode(model))
    } catch {
      print("ERROR: \\(error)")
    }
  }
}
"""

private let reedfrogUlamSwift = """
// Reedfrog.ulam.swift
//
// Phase 5.5 Slice G ulam-port input: Statistical Rethinking
// chapter-13-style reedfrog model with two-grouping multilevel
// structure — a per-tank random intercept `a[tank]` plus a per-size
// random offset `s[size]`. Demonstrates that Phase 5's vector-
// parameter + index-column accumulators handle two independent
// indexed groupings.
//
// Regenerate the .stan + .data.json + cmdstan output artifacts with:
//
//   stan ulam --model Reedfrog [-V]
//
// Or run this file standalone to print just the Stan source:
//
//   cd ~/Projects/Swift/SwiftStan
//   swiftc -parse-as-library -o /tmp/ulam_reedfrog \\
//     Sources/SwiftStan/Ulam/AST/*.swift \\
//     Sources/SwiftStan/Ulam/Builder/*.swift \\
//     Sources/SwiftStan/Ulam/Data/*.swift \\
//     Sources/SwiftStan/Ulam/Generator/*.swift \\
//     ~/Documents/StanCases/reedfrog/Preliminaries/Reedfrog.ulam.swift
//   /tmp/ulam_reedfrog

@main
struct ReedfrogSmoke {
  static func main() {
    let data: UlamData = [
      "y":       .integer([3, 5, 4, 2, 7, 8, 6, 7, 4, 5, 3, 6, 8, 9, 7, 8]),
      "density": .integer([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]),
      "tank":    .integer([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]),
      "size":    .integer([1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2]),
    ]

    let model = UlamModel(data: data) {
      Likelihood("y", .binomial(n: "density", p: "p"))
      Link(.logit, lhs: "p", rhs: "a[tank] + s[size]")
      VaryingPrior("a", indexedBy: "tank", .normal("a_bar", "sigma_a"))
      VaryingPrior("s", indexedBy: "size", .normal(0, "sigma_s"))
      Prior("a_bar", .normal(0, 1.5))
      Prior("sigma_a", .normal(0, 1), truncation: Truncation(lower: 0))
      Prior("sigma_s", .normal(0, 1), truncation: Truncation(lower: 0))
    }

    do {
      print(try stancode(model))
    } catch {
      print("ERROR: \\(error)")
    }
  }
}
"""
