//
//  StanBlockParser.swift
//  Stan
//
//  Slice B of Docs/Stan2AlistCommandPlan.md — a line/block parser for the
//  subset of Stan that `stancode` emits plus the idiomatic hand-written
//  shapes (radon_pp.stan). It splits the source into blocks, strips
//  comments, and parses `data` / `parameters` declarations and `model`
//  statements into a `StanProgram`.
//
//  `transformed data`, `transformed parameters`, and `functions` are
//  recognised and recorded in `droppedBlocks` (Slice C warns), but
//  their bodies are not interpreted. `generated quantities` is now
//  parsed — each `<type>[N] <name> = <dist>_rng(args);` line becomes
//  a `StanModelStatement.assignment` in `StanProgram.gqStatements`.
//
//  The parser fails loud: any block we don't recognise, any declaration
//  or model statement we can't parse, throws `StanBlockParseError`
//  rather than silently dropping content. This keeps the "round-trip /
//  idiomatic-Stan only" contract honest.
//

import Foundation

enum StanBlockParser {

  /// Blocks whose contents we parse into the program.
  private static let translatedBlocks: Set<String> = [
    "data", "parameters", "model", "generated quantities",
  ]
  /// Blocks we recognise but deliberately skip (recorded as dropped).
  private static let skippedBlocks: [String] = [
    "transformed data",
    "transformed parameters",
    "functions",
  ]

  static func parse(_ source: String) throws -> StanProgram {
    var program = StanProgram(dataDecls: [],
                              parameterDecls: [],
                              modelStatements: [],
                              gqStatements: [],
                              droppedBlocks: [])
    // Strip comments up front so a leading/inter-block comment (e.g. the
    // generator's `// Generated by SwiftStan ulam port.` banner) doesn't
    // read as an unrecognized top-level construct.
    var rest = Substring(stripComments(source))

    while true {
      // Skip leading whitespace between blocks.
      rest = Substring(rest.drop { $0.isWhitespace })
      if rest.isEmpty { break }

      guard let (header, body, remainder) = try nextBlock(rest) else {
        throw StanBlockParseError.unrecognizedTopLevel(snippet(rest))
      }
      rest = remainder

      if translatedBlocks.contains(header) {
        switch header {
        case "data":
          program.dataDecls += try parseDeclarations(body)
        case "parameters":
          program.parameterDecls += try parseDeclarations(body)
        case "model":
          program.modelStatements += try parseModelStatements(body)
        case "generated quantities":
          program.gqStatements += try parseModelStatements(body)
        default:
          break
        }
      } else {
        program.droppedBlocks.append(header)
      }
    }
    return program
  }

  // MARK: - Block splitting

  /// Read the next `header { body }` from the front of `source`. Returns
  /// the recognised header name, the brace body, and the remainder after
  /// the closing brace. Returns nil only when no recognised header
  /// matches (caller turns that into a fail-loud error).
  private static func nextBlock(
    _ source: Substring
  ) throws -> (header: String, body: String, remainder: Substring)? {
    guard let header = matchHeader(source) else { return nil }
    // Advance past the header to its opening brace.
    let afterHeader = source.dropFirst(header.count)
    guard let openRel = afterHeader.firstIndex(of: "{") else {
      throw StanBlockParseError.unterminatedBlock(header)
    }
    var depth = 0
    var idx = openRel
    while idx < afterHeader.endIndex {
      let c = afterHeader[idx]
      if c == "{" { depth += 1 }
      else if c == "}" {
        depth -= 1
        if depth == 0 {
          let bodyStart = afterHeader.index(after: openRel)
          let body = String(afterHeader[bodyStart..<idx])
          let remainder = afterHeader[afterHeader.index(after: idx)...]
          return (header, body, remainder)
        }
      }
      idx = afterHeader.index(after: idx)
    }
    throw StanBlockParseError.unterminatedBlock(header)
  }

  /// The recognised block header at the front of `source`, if any. Tries
  /// the two-word skipped headers before single-word ones so
  /// "transformed data" wins over a bare "data"-like prefix.
  private static func matchHeader(_ source: Substring) -> String? {
    let candidates = skippedBlocks + Array(translatedBlocks)
    // Longest first so "transformed parameters" beats "parameters".
    for header in candidates.sorted(by: { $0.count > $1.count }) {
      if matches(source, header: header) { return header }
    }
    return nil
  }

  /// True when `source` begins with `header` followed by whitespace or a
  /// brace — guards against "data" matching inside "database".
  private static func matches(_ source: Substring, header: String) -> Bool {
    // Normalise internal whitespace in the header ("transformed data"
    // may appear with multiple spaces / a newline between the words).
    let words = header.split(separator: " ")
    var cursor = source
    for (i, word) in words.enumerated() {
      cursor = Substring(cursor.drop { $0.isWhitespace })
      guard cursor.hasPrefix(word) else { return false }
      cursor = cursor.dropFirst(word.count)
      if i == words.count - 1 {
        // After the final word we need whitespace or the opening brace.
        guard let next = cursor.first else { return false }
        return next.isWhitespace || next == "{"
      }
    }
    return false
  }

  // MARK: - Declarations

  private static func parseDeclarations(_ body: String) throws -> [StanDecl] {
    let stripped = stripComments(body)
    let statements = splitStatements(stripped)
    return try statements.map(parseDeclaration)
  }

  private static func parseDeclaration(_ raw: String) throws -> StanDecl {
    let collapsed = collapseWhitespace(raw)
    guard let name = lastIdentifier(in: collapsed) else {
      throw StanBlockParseError.malformedDeclaration(raw)
    }
    // The spec is everything before the trailing name.
    guard let nameRange = collapsed.range(of: name, options: .backwards) else {
      throw StanBlockParseError.malformedDeclaration(raw)
    }
    var spec = String(collapsed[..<nameRange.lowerBound])
      .trimmingCharacters(in: .whitespaces)

    // Pull out a `<...>` constraint block, if present.
    var constraints = StanConstraints.none
    if let lt = spec.firstIndex(of: "<"),
       let gt = matchingAngle(spec, from: lt) {
      let inner = String(spec[spec.index(after: lt)..<gt])
      constraints = try parseConstraints(inner, raw: raw)
      spec.removeSubrange(lt...gt)
      spec = collapseWhitespace(spec).trimmingCharacters(in: .whitespaces)
    }

    let type = classifyType(spec)
    return StanDecl(name: name, type: type, constraints: constraints, raw: collapsed)
  }

  private static func classifyType(_ spec: String) -> StanType {
    let s = spec.trimmingCharacters(in: .whitespaces)
    if s.hasPrefix("array[") {
      let outer = bracketContents(s, after: "array") ?? "N"
      // `array[<outer>] vector[<length>]` — varying-vector parameter.
      if let vecRange = s.range(of: "vector[") {
        let rest = String(s[vecRange.lowerBound...])
        if let length = bracketContents(rest, after: "vector") {
          return .arrayVector(outer: outer, length: length)
        }
      }
      if s.contains(" int") || s.hasSuffix("int") { return .arrayInt(size: outer) }
      if s.contains(" real") || s.hasSuffix("real") { return .arrayReal(size: outer) }
      return .other(s)
    }
    if s.hasPrefix("vector") {
      if let size = bracketContents(s, after: "vector") { return .vector(size: size) }
      return .other(s)
    }
    if s.hasPrefix("cholesky_factor_corr") {
      if let dim = bracketContents(s, after: "cholesky_factor_corr") {
        return .cholFactorCorr(dim: dim)
      }
      return .other(s)
    }
    if s.hasPrefix("cov_matrix") {
      if let dim = bracketContents(s, after: "cov_matrix") { return .covMatrix(dim: dim) }
      return .other(s)
    }
    if s.hasPrefix("matrix[") {
      // `matrix[<rows>, <cols>]` — split bracket contents on the top-level comma.
      if let inner = bracketContents(s, after: "matrix") {
        let parts = inner.split(separator: ",", maxSplits: 1).map {
          $0.trimmingCharacters(in: .whitespaces)
        }
        if parts.count == 2 { return .matrix(rows: parts[0], cols: parts[1]) }
      }
      return .other(s)
    }
    if s == "real" { return .real }
    if s == "int" { return .int }
    return .other(s)
  }

  private static func parseConstraints(_ inner: String, raw: String) throws -> StanConstraints {
    var c = StanConstraints.none
    for pair in splitTopLevelCommas(inner) {
      let kv = pair.split(separator: "=", maxSplits: 1).map {
        $0.trimmingCharacters(in: .whitespaces)
      }
      guard kv.count == 2 else {
        throw StanBlockParseError.malformedDeclaration(raw)
      }
      switch kv[0] {
      case "lower":      c.lower = kv[1]
      case "upper":      c.upper = kv[1]
      case "offset":     c.offset = kv[1]
      case "multiplier": c.multiplier = kv[1]
      default:
        throw StanBlockParseError.malformedDeclaration(raw)
      }
    }
    return c
  }

  // MARK: - Model statements

  private static func parseModelStatements(_ body: String) throws -> [StanModelStatement] {
    let stripped = stripComments(body)
    // The forward emitter wraps a non-vectorising linear predictor in a
    // single per-row `for (i in 1:N) { lhs[i] = rhs; }` loop (the
    // contract in Docs/LoopEmissionPlan.md). Rewrite each such loop back
    // into the equivalent vectorised assignment by dropping the `[i]`
    // subscripts — the inverse of BlockEmitter.renderLoopBody — so the
    // rest of the pipeline treats it like any other assignment. Anything
    // off that contract (`while`, non-`1:N` bounds, multi-statement or
    // nested bodies, stray braces) fails loud with `unsupportedLoop`.
    let normalised = try rewriteContractLoops(stripped)
    let statements = splitStatements(normalised)
    return try statements.compactMap(parseModelStatement)
  }

  // MARK: - Contract-loop rewriting (inverse of BlockEmitter loop emission)

  /// Walk the model body, copying text verbatim except for contract
  /// `for (i in 1:N) { … }` loops, which are rewritten in place into a
  /// `;`-terminated vectorised assignment. `while`, stray braces, and any
  /// loop that doesn't match the single-assignment contract throw.
  private static func rewriteContractLoops(_ body: String) throws -> String {
    let chars = Array(body)
    var out = ""
    var i = 0
    while i < chars.count {
      if let kw = keyword(at: i, in: chars) {
        if kw == "while" { throw StanBlockParseError.unsupportedLoop }
        i = try appendRewrittenForLoop(chars, from: i, into: &out)
        continue
      }
      let c = chars[i]
      // Any brace outside a recognised contract loop is off-contract.
      if c == "{" || c == "}" { throw StanBlockParseError.unsupportedLoop }
      out.append(c)
      i += 1
    }
    return out
  }

  /// The `for`/`while` keyword starting at `i` (token boundaries on both
  /// sides), or nil. Avoids matching identifiers like `format`.
  private static func keyword(at i: Int, in chars: [Character]) -> String? {
    func matches(_ word: String) -> Bool {
      let w = Array(word)
      guard i + w.count <= chars.count else { return false }
      for k in 0..<w.count where chars[i + k] != w[k] { return false }
      let boundaryBefore = i == 0 || !isIdentifierChar(chars[i - 1])
      let after = i + w.count
      let boundaryAfter = after >= chars.count || !isIdentifierChar(chars[after])
      return boundaryBefore && boundaryAfter
    }
    if matches("for") { return "for" }
    if matches("while") { return "while" }
    return nil
  }

  /// Parse a contract `for (i in 1:N) { lhs[i] = rhs; }` starting at the
  /// `for` keyword, append the de-subscripted `lhs = rhs;` to `out`, and
  /// return the index just past the closing brace.
  private static func appendRewrittenForLoop(_ chars: [Character],
                                             from start: Int,
                                             into out: inout String) throws -> Int {
    var i = start + 3 // past "for"
    while i < chars.count, chars[i].isWhitespace { i += 1 }
    guard i < chars.count, chars[i] == "(",
          let closeParen = matchingDelimiterIndex(chars, from: i,
                                                  openChar: "(", closeChar: ")") else {
      throw StanBlockParseError.unsupportedLoop
    }
    let header = String(chars[(i + 1)..<closeParen]).trimmingCharacters(in: .whitespaces)
    guard let loopVar = contractLoopVar(header) else {
      throw StanBlockParseError.unsupportedLoop
    }

    i = closeParen + 1
    while i < chars.count, chars[i].isWhitespace { i += 1 }
    guard i < chars.count, chars[i] == "{",
          let closeBrace = matchingDelimiterIndex(chars, from: i,
                                                  openChar: "{", closeChar: "}") else {
      throw StanBlockParseError.unsupportedLoop
    }
    let inner = String(chars[(i + 1)..<closeBrace])
    // Reject nested loops/blocks before splitting the body.
    if inner.contains("{")
        || inner.range(of: #"\b(for|while)\b"#, options: .regularExpression) != nil {
      throw StanBlockParseError.unsupportedLoop
    }
    let bodyStatements = splitStatements(inner)
    if bodyStatements.count == 1 {
      let stmt = bodyStatements[0]
      // Contract body: single assignment `lhs[i] = rhs`, never a sampling statement.
      guard stmt.contains("="), !stmt.contains("~") else {
        throw StanBlockParseError.unsupportedLoop
      }
      out.append(desubscript(stmt, loopVar: loopVar))
      out.append(";")
    } else if bodyStatements.count == 2 {
      // SUR contract body: `row_vector[<dim>] <local> = <rhs>; <outcome>[n] ~ <dist>;`
      // Lower to two flat statements, keeping rhs verbatim (BlockEmitter reads it back
      // via detectSurLoops and re-emits the loop identically).
      try appendRewrittenSurLoop(bodyStatements, loopVar: loopVar, into: &out)
    } else {
      throw StanBlockParseError.unsupportedLoop
    }
    return closeBrace + 1
  }

  /// Rewrite a two-statement SUR loop body into two flat model statements.
  ///
  /// Contract shape (BlockEmitter SUR Slices D+E):
  ///   `row_vector[<dim>] <local> = <rhs>;`
  ///   `<outcome>[<n>] ~ multi_normal(<local>, <cov>);`
  ///
  /// Lowers to:
  ///   `<local> = <rhs>;`          — assignment, RHS kept verbatim
  ///   `<outcome> ~ multi_normal(<local>, <cov>);`  — sampling, `[n]` stripped
  private static func appendRewrittenSurLoop(_ stmts: [String],
                                             loopVar: String,
                                             into out: inout String) throws {
    let s0 = collapseWhitespace(stmts[0]).trimmingCharacters(in: .whitespaces)
    let s1 = collapseWhitespace(stmts[1]).trimmingCharacters(in: .whitespaces)

    // First statement: `row_vector[<dim>] <local> = <rhs>`
    // Strip the leading type spec (`row_vector[<dim>]`) to get `local = rhs`.
    guard let eqRange0 = s0.range(of: "="),
          !s0.contains("~") else {
      throw StanBlockParseError.unsupportedLoop
    }
    let lhsFull0 = String(s0[..<eqRange0.lowerBound]).trimmingCharacters(in: .whitespaces)
    let rhs0     = String(s0[eqRange0.upperBound...]).trimmingCharacters(in: .whitespaces)
    // The local name is the last identifier in the possibly-typed LHS.
    guard let localName = lastIdentifier(in: lhsFull0), !localName.isEmpty else {
      throw StanBlockParseError.unsupportedLoop
    }
    // Emit the assignment with the RHS verbatim (BlockEmitter's detectSurLoops
    // re-reads `meanRhsSource` from .deterministic's rhs.source).
    out.append("\(localName) = \(rhs0);")

    // Second statement: `<outcome>[<loopVar>] ~ <dist>(<args>)`
    guard s1.contains("~") else { throw StanBlockParseError.unsupportedLoop }
    // Strip the `[<loopVar>]` subscript from the outcome LHS.
    let normalised1 = desubscript(s1, loopVar: loopVar)
    out.append(normalised1)
    out.append(";")
  }

  /// Validate a contract loop header `i in 1:N` and return the loop
  /// variable. The forward emitter always emits the `1:N` bound; any
  /// other range is off-contract.
  private static func contractLoopVar(_ header: String) -> String? {
    let pattern = #"^([A-Za-z_]\w*)\s+in\s+1\s*:\s*N$"#
    guard let re = try? NSRegularExpression(pattern: pattern) else { return nil }
    let range = NSRange(header.startIndex..., in: header)
    guard let m = re.firstMatch(in: header, range: range), m.numberOfRanges >= 2,
          let r = Range(m.range(at: 1), in: header) else { return nil }
    return String(header[r])
  }

  /// Drop every `[<loopVar>]` subscript — the exact inverse of
  /// `renderLoopBody`, which only ever appends `[<loopVar>]` to data
  /// vectors / index columns. `a_actor[actor[i]]` → `a_actor[actor]`,
  /// `condition[i]` → `condition`, `p[i] = …` → `p = …`.
  private static func desubscript(_ s: String, loopVar: String) -> String {
    let pattern = "\\[\\s*\(loopVar)\\s*\\]"
    let collapsed = s.replacingOccurrences(of: pattern, with: "",
                                           options: .regularExpression)
    return collapseWhitespace(collapsed).trimmingCharacters(in: .whitespaces)
  }

  private static func matchingDelimiterIndex(_ chars: [Character],
                                             from openIdx: Int,
                                             openChar: Character,
                                             closeChar: Character) -> Int? {
    var depth = 0
    var idx = openIdx
    while idx < chars.count {
      if chars[idx] == openChar { depth += 1 }
      else if chars[idx] == closeChar {
        depth -= 1
        if depth == 0 { return idx }
      }
      idx += 1
    }
    return nil
  }

  /// Stan type keywords that begin a model-block local declaration
  /// (e.g. `vector[N] p;` — the generator declares derived linear
  /// predictors before assigning them). Such declarations carry no
  /// statement meaning for the reverse and are skipped.
  private static let typeKeywords: Set<String> = [
    "vector", "row_vector", "matrix", "real", "int", "array", "simplex",
    "ordered", "positive_ordered", "unit_vector", "cov_matrix",
    "corr_matrix", "cholesky_factor_corr", "cholesky_factor_cov",
  ]

  private static func parseModelStatement(_ raw: String) throws -> StanModelStatement? {
    let s = collapseWhitespace(raw).trimmingCharacters(in: .whitespaces)
    if let tildeRange = s.range(of: "~") {
      let lhs = String(s[..<tildeRange.lowerBound]).trimmingCharacters(in: .whitespaces)
      let rhs = String(s[tildeRange.upperBound...]).trimmingCharacters(in: .whitespaces)
      return try parseSampling(lhs: lhs, rhs: rhs, raw: raw)
    }
    if let eqRange = s.range(of: "=") {
      let lhs = String(s[..<eqRange.lowerBound]).trimmingCharacters(in: .whitespaces)
      let rhs = String(s[eqRange.upperBound...]).trimmingCharacters(in: .whitespaces)
      guard !lhs.isEmpty, !rhs.isEmpty else {
        throw StanBlockParseError.malformedModelStatement(raw)
      }
      return .assignment(lhs: lhs, rhs: rhs)
    }
    // No `~` or `=`: a bare local declaration (`vector[N] p`) — skip it.
    if let firstWord = s.split(whereSeparator: { $0 == " " || $0 == "[" }).first,
       typeKeywords.contains(String(firstWord)) {
      return nil
    }
    throw StanBlockParseError.malformedModelStatement(raw)
  }

  private static func parseSampling(lhs: String,
                                    rhs: String,
                                    raw: String) throws -> StanModelStatement {
    guard !lhs.isEmpty,
          let openParen = rhs.firstIndex(of: "(") else {
      throw StanBlockParseError.malformedModelStatement(raw)
    }
    let distName = String(rhs[..<openParen]).trimmingCharacters(in: .whitespaces)
    guard !distName.isEmpty,
          let closeParen = matchingParen(rhs, from: openParen) else {
      throw StanBlockParseError.malformedModelStatement(raw)
    }
    let argsInner = String(rhs[rhs.index(after: openParen)..<closeParen])
    let args = splitTopLevelCommas(argsInner)
      .map { $0.trimmingCharacters(in: .whitespaces) }
      .filter { !$0.isEmpty }

    // Anything after the `)` must be a `T[...]` truncation suffix.
    let tail = String(rhs[rhs.index(after: closeParen)...])
      .trimmingCharacters(in: .whitespaces)
    var truncation: StanTruncation? = nil
    if !tail.isEmpty {
      guard tail.hasPrefix("T["), tail.hasSuffix("]") else {
        throw StanBlockParseError.malformedModelStatement(raw)
      }
      let inner = String(tail.dropFirst(2).dropLast())
      let parts = splitTopLevelCommas(inner).map {
        $0.trimmingCharacters(in: .whitespaces)
      }
      let lower = parts.indices.contains(0) && !parts[0].isEmpty ? parts[0] : nil
      let upper = parts.indices.contains(1) && !parts[1].isEmpty ? parts[1] : nil
      truncation = StanTruncation(lower: lower, upper: upper)
    }
    return .sampling(lhs: lhs, distName: distName, args: args, truncation: truncation)
  }

  // MARK: - Lexical helpers

  /// Remove `//` line comments and `/* ... */` block comments.
  private static func stripComments(_ s: String) -> String {
    var out = ""
    let chars = Array(s)
    var i = 0
    while i < chars.count {
      if chars[i] == "/", i + 1 < chars.count, chars[i + 1] == "/" {
        while i < chars.count, chars[i] != "\n" { i += 1 }
      } else if chars[i] == "/", i + 1 < chars.count, chars[i + 1] == "*" {
        i += 2
        while i + 1 < chars.count, !(chars[i] == "*" && chars[i + 1] == "/") { i += 1 }
        i += 2
      } else {
        out.append(chars[i])
        i += 1
      }
    }
    return out
  }

  /// Split a block body into individual `;`-terminated statements,
  /// trimming and dropping empties.
  private static func splitStatements(_ s: String) -> [String] {
    s.components(separatedBy: ";")
      .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
      .filter { !$0.isEmpty }
  }

  private static func collapseWhitespace(_ s: String) -> String {
    s.replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
  }

  private static func lastIdentifier(in declaration: String) -> String? {
    let chars = Array(declaration.trimmingCharacters(in: .whitespaces))
    guard !chars.isEmpty else { return nil }
    var end = chars.count
    while end > 0, !isIdentifierChar(chars[end - 1]) { end -= 1 }
    var start = end
    while start > 0, isIdentifierChar(chars[start - 1]) { start -= 1 }
    guard start < end else { return nil }
    return String(chars[start..<end])
  }

  private static func isIdentifierChar(_ c: Character) -> Bool {
    c.isLetter || c.isNumber || c == "_"
  }

  /// Contents of the `[...]` immediately following `prefix` in `spec`,
  /// e.g. `bracketContents("array[N] int", after: "array")` → "N".
  private static func bracketContents(_ spec: String, after prefix: String) -> String? {
    guard let prefixRange = spec.range(of: prefix) else { return nil }
    let afterPrefix = spec[prefixRange.upperBound...]
    guard let open = afterPrefix.firstIndex(of: "["),
          let close = afterPrefix.firstIndex(of: "]"),
          open < close else { return nil }
    return String(afterPrefix[afterPrefix.index(after: open)..<close])
      .trimmingCharacters(in: .whitespaces)
  }

  private static func matchingParen(_ s: String, from open: String.Index) -> String.Index? {
    matchingDelimiter(s, from: open, open: "(", close: ")")
  }

  private static func matchingAngle(_ s: String, from open: String.Index) -> String.Index? {
    matchingDelimiter(s, from: open, open: "<", close: ">")
  }

  private static func matchingDelimiter(_ s: String,
                                        from open: String.Index,
                                        open openChar: Character,
                                        close closeChar: Character) -> String.Index? {
    var depth = 0
    var idx = open
    while idx < s.endIndex {
      let c = s[idx]
      if c == openChar { depth += 1 }
      else if c == closeChar {
        depth -= 1
        if depth == 0 { return idx }
      }
      idx = s.index(after: idx)
    }
    return nil
  }

  /// Split on commas that sit at bracket/paren depth 0, so
  /// `alpha[county] + beta*floor, sigma` → ["alpha[county] + beta*floor", "sigma"].
  private static func splitTopLevelCommas(_ s: String) -> [String] {
    var parts: [String] = []
    var current = ""
    var depth = 0
    for c in s {
      switch c {
      case "(", "[", "<": depth += 1; current.append(c)
      case ")", "]", ">": depth -= 1; current.append(c)
      case "," where depth == 0:
        parts.append(current)
        current = ""
      default:
        current.append(c)
      }
    }
    if !current.trimmingCharacters(in: .whitespaces).isEmpty || !parts.isEmpty {
      parts.append(current)
    }
    return parts
  }

  private static func snippet(_ s: Substring) -> String {
    String(s.prefix(40)).trimmingCharacters(in: .whitespacesAndNewlines)
  }
}
